# DO NOT EDIT: autogenerated by "apply_tactics_generated.py"

TDATA = {}
# pulled from "tactics_work/kalah-results-1-4-0-0-0.json" :
TDATA[(1, 4, 0, 0, 0)] = \
    [0, 1073, 0, 0, 0, 535, 1, 0, 1, -1, -1, 1, 0, 1, -1227, 1, -1632, 429]
# pulled from "tactics_work/kalah-results-1-4-0-0-1.json" :
TDATA[(1, 4, 0, 0, 1)] = \
    [0, 0, 0, 0, 686, 1, 0, 0, 0, 0, 1, 0, 0, 1, -666, 1, 0, 1]
# pulled from "tactics_work/kalah-results-1-4-0-0-2.json" :
TDATA[(1, 4, 0, 0, 2)] = \
    [-1, 780, -668, 2, -289, 0, 1, 1, 4, -1, -2, -2, 1, 2, -2421, -403, 0, 176]
# pulled from "tactics_work/kalah-results-1-4-0-0-3.json" :
TDATA[(1, 4, 0, 0, 3)] = \
    [-1, -2, 0, -533, -731, 0, 0, 0, 0, 2, -2, 0, 0, 274, -558, -592, 0, -1]
# pulled from "tactics_work/kalah-results-1-4-0-1-0.json" :
TDATA[(1, 4, 0, 1, 0)] = \
    [0, 1062, 0, 0, -1900, 0, -1, -1, -5, 3, 0, 0, 1, -26, 0, -1203, -1997, 0]
# pulled from "tactics_work/kalah-results-1-4-0-1-1.json" :
TDATA[(1, 4, 0, 1, 1)] = \
    [0, -1647, -124, -595, 0, 0, 2, 0, 0, 0, -3, -1, 544, -302, 205, 309, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-0-1-2.json" :
TDATA[(1, 4, 0, 1, 2)] = \
    [1435, -917, -1, -2254, 0, 1406, 6, -1, 0, 4, 0, 3, 1138, -820, -41, -1, -1, 938]
# pulled from "tactics_work/kalah-results-1-4-0-1-3.json" :
TDATA[(1, 4, 0, 1, 3)] = \
    [-1, -1, 1, 565, 0, 1, -1, -7, 0, 0, 0, 0, 0, 0, -1959, -658, 1, 2037]
# pulled from "tactics_work/kalah-results-1-4-0-2-0.json" :
TDATA[(1, 4, 0, 2, 0)] = \
    [0, -1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, -1, -1, 0]
# pulled from "tactics_work/kalah-results-1-4-0-2-1.json" :
TDATA[(1, 4, 0, 2, 1)] = \
    [1, 0, -538, -1677, 0, 0, 1, 3, -4, -2, -3, 0, 0, -1942, 2, -731, 0, 660]
# pulled from "tactics_work/kalah-results-1-4-0-2-2.json" :
TDATA[(1, 4, 0, 2, 2)] = \
    [1764, 283, 1, 0, 337, 0, 0, 0, 0, 0, -1, 0, 0, 453, 1, 0, -1, 516]
# pulled from "tactics_work/kalah-results-1-4-0-2-3.json" :
TDATA[(1, 4, 0, 2, 3)] = \
    [-1, 0, 0, 0, -1, 1644, 1, 0, -1, 0, 0, 0, 0, -1, 663, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-0-0.json" :
TDATA[(1, 4, 3, 0, 0)] = \
    [-380, 874, -1, -1042, -848, -2751, 1, 4, 1, 0, 0, 0, -1, -2, 0, -953, -1028, 0]
# pulled from "tactics_work/kalah-results-1-4-3-0-1.json" :
TDATA[(1, 4, 3, 0, 1)] = \
    [-1442, -1367, 0, 1, 0, 1739, 0, 4, 0, 0, 0, 6, 2, -293, 84, 512, -668, 866]
# pulled from "tactics_work/kalah-results-1-4-3-0-2.json" :
TDATA[(1, 4, 3, 0, 2)] = \
    [-2055, -1, -1757, 1, 630, 119, 0, 0, 0, 0, 1, 0, 149, 2, 0, -1, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-3-0-3.json" :
TDATA[(1, 4, 3, 0, 3)] = \
    [1, 0, 663, -1420, -1344, -1093, 0, 3, -3, 0, -1, 1, 0, 0, 0, 0, 0, 1]
# pulled from "tactics_work/kalah-results-1-4-3-1-0.json" :
TDATA[(1, 4, 3, 1, 0)] = \
    [-221, -458, 1, -3164, 0, 0, -1, 3, -5, 1, -2, 0, 0, 1, 1, 0, -1968, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-1.json" :
TDATA[(1, 4, 3, 1, 1)] = \
    [-1985, 1608, 0, 1612, 1039, -1915, 4, 3, -1, -2, -4, -2, 0, -3, -1, -172, -727, 1136]
# pulled from "tactics_work/kalah-results-1-4-3-1-2.json" :
TDATA[(1, 4, 3, 1, 2)] = \
    [0, 0, 0, 0, -649, 0, 2, -1, 1, 0, -4, -1, 0, 0, 0, 0, 385, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-3.json" :
TDATA[(1, 4, 3, 1, 3)] = \
    [0, 650, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-2-0.json" :
TDATA[(1, 4, 3, 2, 0)] = \
    [1667, 0, 0, 0, 1307, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 493, -1, 0]
# pulled from "tactics_work/kalah-results-1-4-3-2-1.json" :
TDATA[(1, 4, 3, 2, 1)] = \
    [-264, 721, 0, -1, -1, 1297, 0, -2, 1, 0, -1, -3, 0, 0, -363, -1, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-2-2.json" :
TDATA[(1, 4, 3, 2, 2)] = \
    [0, 0, 923, 0, 0, 0, 0, 0, -1, 0, -3, 2, 39, -532, 0, 1889, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-2-3.json" :
TDATA[(1, 4, 3, 2, 3)] = \
    [570, 0, 972, 0, 0, 228, 2, -1, 7, 0, 0, 4, 1, 0, 0, 0, 0, 272]
# pulled from "tactics_work/kalah-results-1-3-0-0-0.json" :
TDATA[(1, 3, 0, 0, 0)] = \
    [0, 1816, 0, 0, -848, 1, 0, 0, 0, -1, 0, 0, 0, 0, 1, -477, 0, -1042]
# pulled from "tactics_work/kalah-results-1-3-0-0-1.json" :
TDATA[(1, 3, 0, 0, 1)] = \
    [0, -187, -1931, 0, -2475, 1019, 0, 1, 1, 0, 5, 0, -1436, 0, 0, 1, -1187, -1122]
# pulled from "tactics_work/kalah-results-1-3-0-0-2.json" :
TDATA[(1, 3, 0, 0, 2)] = \
    [0, 0, 0, 2496, -2, 545, 0, -5, 0, -1, 0, 0, -2936, 0, -1601, -1, 1, 3282]
# pulled from "tactics_work/kalah-results-1-3-0-0-3.json" :
TDATA[(1, 3, 0, 0, 3)] = \
    [1983, 218, -484, 1808, 0, -444, -1, 0, 0, 5, -1, 2, -985, 1127, -1449, -1, -51, 0]
# pulled from "tactics_work/kalah-results-1-3-0-1-0.json" :
TDATA[(1, 3, 0, 1, 0)] = \
    [0, 1278, -1, 0, 0, 0, 0, 1, 1, 0, 0, 0, -256, 0, 0, 0, 0, -1963]
# pulled from "tactics_work/kalah-results-1-3-0-1-1.json" :
TDATA[(1, 3, 0, 1, 1)] = \
    [-765, -1951, 0, 1559, 1158, -1963, 1, 0, -1, -4, 3, 0, -628, 993, 1, 0, -657, -1610]
# pulled from "tactics_work/kalah-results-1-3-0-1-2.json" :
TDATA[(1, 3, 0, 1, 2)] = \
    [0, 0, -1707, 0, 1729, 1380, 0, 2, 1, -2, -1, 2, 0, 0, 283, 0, 1, -1705]
# pulled from "tactics_work/kalah-results-1-3-0-1-3.json" :
TDATA[(1, 3, 0, 1, 3)] = \
    [-1928, 0, -2, -78, 0, 628, -5, 0, 1, -4, 1, -10, 0, 1115, 654, 2, 1325, 1287]
# pulled from "tactics_work/kalah-results-1-3-0-2-0.json" :
TDATA[(1, 3, 0, 2, 0)] = \
    [0, 0, 0, 0, 0, 0, 0, 0, 0, -4, -4, -1, 0, 1489, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-0-2-1.json" :
TDATA[(1, 3, 0, 2, 1)] = \
    [0, -2068, 876, 0, 1635, -1047, 1, 1, 0, 2, -1, 1, 58, 1, 0, 258, 0, 728]
# pulled from "tactics_work/kalah-results-1-3-0-2-2.json" :
TDATA[(1, 3, 0, 2, 2)] = \
    [-1, 0, 0, 993, 0, -825, 0, 0, 0, 0, 0, 1, 0, 584, 1, 0, -1, 0]
# pulled from "tactics_work/kalah-results-1-3-0-2-3.json" :
TDATA[(1, 3, 0, 2, 3)] = \
    [0, 0, 1, 0, 1, -202, 0, 6, 0, 1, 0, 2, -1, 0, 0, -1774, 2185, 0]
# pulled from "tactics_work/kalah-results-1-3-3-0-0.json" :
TDATA[(1, 3, 3, 0, 0)] = \
    [0, 1740, 818, -1917, -448, 2226, -1, 0, 4, 1, 0, -1, 0, 0, 0, -1625, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-3-0-1.json" :
TDATA[(1, 3, 3, 0, 1)] = \
    [-1984, 257, -1, 1368, -1, 433, -1, 0, 2, 0, -1, 0, 0, 0, -1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-3-0-2.json" :
TDATA[(1, 3, 3, 0, 2)] = \
    [-647, -918, 0, 0, 0, 1815, 1, 5, 3, 1, 4, 3, -1937, 1352, 0, -2366, 0, -2]
# pulled from "tactics_work/kalah-results-1-3-3-0-3.json" :
TDATA[(1, 3, 3, 0, 3)] = \
    [0, 0, -1846, 0, 0, 0, 0, 0, 5, -1, 0, -3, 0, 0, 0, 0, 1975, -1767]
# pulled from "tactics_work/kalah-results-1-3-3-1-0.json" :
TDATA[(1, 3, 3, 1, 0)] = \
    [-1527, -1, -171, 0, 0, -1, -1, 0, 0, 0, 1, -1, 0, 0, 0, 0, 2858, -1765]
# pulled from "tactics_work/kalah-results-1-3-3-1-1.json" :
TDATA[(1, 3, 3, 1, 1)] = \
    [-1916, 571, 0, 0, 923, 0, 0, -2, 0, 2, 2, 0, 0, -1, 0, -1, 1466, 0]
# pulled from "tactics_work/kalah-results-1-3-3-1-2.json" :
TDATA[(1, 3, 3, 1, 2)] = \
    [-1647, 0, 1637, 0, -1, 0, 0, -5, 0, 1, 0, 0, 1363, 0, 0, -1882, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-3-1-3.json" :
TDATA[(1, 3, 3, 1, 3)] = \
    [-953, 1, 0, 0, -1999, 1869, 0, 2, 1, 0, 2, -1, -2, 1896, 1751, 116, -1, 1]
# pulled from "tactics_work/kalah-results-1-3-3-2-0.json" :
TDATA[(1, 3, 3, 2, 0)] = \
    [1, -1, 0, 0, 0, -1, 0, 0, 0, -2, 0, 0, 0, 0, 1400, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-1.json" :
TDATA[(1, 3, 3, 2, 1)] = \
    [0, -1, 0, 0, 1074, 1821, 0, 0, -3, 0, 0, -1, -1, 1, -1387, 0, -621, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-2.json" :
TDATA[(1, 3, 3, 2, 2)] = \
    [-1216, 0, 1, 0, -1437, 0, 2, 0, 1, 0, 0, 0, 0, 308, -1, -1130, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-3.json" :
TDATA[(1, 3, 3, 2, 3)] = \
    [0, -1489, 1262, 1393, 1991, 1724, -3, -2, 0, 0, 4, 2, 0, -267, -1, 0, -1950, 1]
# pulled from "tactics_work/kalah-results-1-5-0-0-0.json" :
TDATA[(1, 5, 0, 0, 0)] = \
    [-524, 0, 1573, -1523, -1, 1, -1, -2, 5, 0, 0, 7, -280, 0, 0, -453, 1, 0]
# pulled from "tactics_work/kalah-results-1-5-0-0-1.json" :
TDATA[(1, 5, 0, 0, 1)] = \
    [-1, 0, 1958, 1, -283, -24, -1, 1, 2, 5, -1, 2, 376, 0, 1, 0, 103, 0]
# pulled from "tactics_work/kalah-results-1-5-0-0-2.json" :
TDATA[(1, 5, 0, 0, 2)] = \
    [1662, 1, 1, 0, 617, -1, -1, -1, 0, 1, 0, 0, 849, -524, 0, 0, 0, 1]
# pulled from "tactics_work/kalah-results-1-5-0-0-3.json" :
TDATA[(1, 5, 0, 0, 3)] = \
    [-1706, 0, 0, -891, 0, 1, -1, -1, 1, -1, -3, 1, 0, -902, 0, -1, -793, 1941]
# pulled from "tactics_work/kalah-results-1-5-0-1-0.json" :
TDATA[(1, 5, 0, 1, 0)] = \
    [1398, -354, 1, -84, -2, 0, 1, -1, -3, 3, 0, 0, -935, 1273, -1679, 508, 0, 1]
# pulled from "tactics_work/kalah-results-1-5-0-1-1.json" :
TDATA[(1, 5, 0, 1, 1)] = \
    [-10, 136, -98, -366, 651, 0, 0, 0, -1, 0, -3, -1, 1662, 1312, -1646, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-5-0-1-2.json" :
TDATA[(1, 5, 0, 1, 2)] = \
    [-1135, 0, 0, 36, -1675, -1, 3, -2, 0, -4, 0, 0, -1, 0, 0, 0, -595, -910]
# pulled from "tactics_work/kalah-results-1-5-0-1-3.json" :
TDATA[(1, 5, 0, 1, 3)] = \
    [-870, 0, 0, -1257, 0, -1, -1, 3, 4, 3, -1, -2, -2, 205, 1, 321, -1824, -1412]
# pulled from "tactics_work/kalah-results-1-5-0-2-0.json" :
TDATA[(1, 5, 0, 2, 0)] = \
    [1688, 1, 0, 0, 3083, 1, 0, 1, 5, 3, -4, 1, 0, -3, -2, 0, -2033, 0]
# pulled from "tactics_work/kalah-results-1-5-0-2-1.json" :
TDATA[(1, 5, 0, 2, 1)] = \
    [0, 0, 1357, 0, 0, -1, 0, 0, 0, 8, 0, 1, 1, 0, 0, 0, -1882, 0]
# pulled from "tactics_work/kalah-results-1-5-0-2-2.json" :
TDATA[(1, 5, 0, 2, 2)] = \
    [-338, 433, 3036, -1872, -188, -720, 0, -3, 2, 0, 0, -4, 0, 1, -1, 1137, 98, 5]
# pulled from "tactics_work/kalah-results-1-5-0-2-3.json" :
TDATA[(1, 5, 0, 2, 3)] = \
    [-1661, 444, 522, 467, 0, -1, 1, -1, 3, 2, 0, -2, 695, -1, 0, 0, -1858, -1]
# pulled from "tactics_work/kalah-results-1-5-3-0-0.json" :
TDATA[(1, 5, 3, 0, 0)] = \
    [4080, 0, -257, 1, -402, 0, 0, -4, 1, -1, -1, -1, 0, 0, -1020, 1421, 0, 910]
# pulled from "tactics_work/kalah-results-1-5-3-0-1.json" :
TDATA[(1, 5, 3, 0, 1)] = \
    [0, -1685, -776, 1, 0, 0, 1, 0, 0, -3, 1, 0, 181, 0, 0, 0, 704, 0]
# pulled from "tactics_work/kalah-results-1-5-3-0-2.json" :
TDATA[(1, 5, 3, 0, 2)] = \
    [0, -1964, -80, 0, 0, 0, 0, -4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-0-3.json" :
TDATA[(1, 5, 3, 0, 3)] = \
    [1, -779, 0, -626, 1232, 950, 1, 2, -1, -3, 0, -2, 0, -1, 0, 1, 1, -2]
# pulled from "tactics_work/kalah-results-1-5-3-1-0.json" :
TDATA[(1, 5, 3, 1, 0)] = \
    [1955, 0, 0, 1, 0, -1555, 0, -1, 0, 0, 2, 0, 1247, 0, -177, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-1-1.json" :
TDATA[(1, 5, 3, 1, 1)] = \
    [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, -1]
# pulled from "tactics_work/kalah-results-1-5-3-1-2.json" :
TDATA[(1, 5, 3, 1, 2)] = \
    [0, 0, 0, 0, -921, 0, 0, -1, 0, 0, 0, -1, -550, 0, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-5-3-1-3.json" :
TDATA[(1, 5, 3, 1, 3)] = \
    [0, 451, -368, 629, 1434, 967, 0, 0, -1, -2, 0, 0, -1, 0, 1, 651, 1141, 1]
# pulled from "tactics_work/kalah-results-1-5-3-2-0.json" :
TDATA[(1, 5, 3, 2, 0)] = \
    [994, 746, 0, 1, 0, -329, -3, -6, 1, -4, -1, -6, -1, 0, 0, 0, 2, 947]
# pulled from "tactics_work/kalah-results-1-5-3-2-1.json" :
TDATA[(1, 5, 3, 2, 1)] = \
    [0, -76, 0, -1, 3364, -1, -1, 0, 5, 3, -2, 0, 0, 0, 0, 1658, 190, 0]
# pulled from "tactics_work/kalah-results-1-5-3-2-2.json" :
TDATA[(1, 5, 3, 2, 2)] = \
    [-1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-2-3.json" :
TDATA[(1, 5, 3, 2, 3)] = \
    [0, 441, 0, -958, -328, 0, 1, 1, 0, -4, 0, 0, -1772, -1475, 0, 1, 1370, -1]
# pulled from "tactics_work/kalah-results-1-6-0-0-0.json" :
TDATA[(1, 6, 0, 0, 0)] = \
    [-249, 0, 1, 0, 0, 55, 0, 2, -4, 4, 2, 1, -587, 1, 0, 560, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-0-0-1.json" :
TDATA[(1, 6, 0, 0, 1)] = \
    [-1203, 70, -1, -1333, 0, 0, 0, 2, 0, 4, 0, 1, -1197, 0, 0, 2, -1, 0]
# pulled from "tactics_work/kalah-results-1-6-0-0-2.json" :
TDATA[(1, 6, 0, 0, 2)] = \
    [1, 0, -1, 247, -1790, 861, 0, -1, 0, 0, 0, -3, -1634, 0, 1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-0-0-3.json" :
TDATA[(1, 6, 0, 0, 3)] = \
    [-1032, -987, -1, 0, 1, 0, -3, 0, -1, 1, 0, 1, 0, -1, 0, 573, -1, -1558]
# pulled from "tactics_work/kalah-results-1-6-0-1-0.json" :
TDATA[(1, 6, 0, 1, 0)] = \
    [0, -922, 1, 1, 0, 0, 0, 0, 0, -1, 0, 0, 1, 1, -1, 0, -474, -346]
# pulled from "tactics_work/kalah-results-1-6-0-1-1.json" :
TDATA[(1, 6, 0, 1, 1)] = \
    [-726, 0, -285, -700, -429, 1585, -2, 0, -4, 2, 0, -1, -576, 1047, -820, 1380, 0, -2]
# pulled from "tactics_work/kalah-results-1-6-0-1-2.json" :
TDATA[(1, 6, 0, 1, 2)] = \
    [1, 0, 0, 0, 1490, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, -1573, 0]
# pulled from "tactics_work/kalah-results-1-6-0-1-3.json" :
TDATA[(1, 6, 0, 1, 3)] = \
    [-581, -2370, -1186, -187, -3426, 0, 1, -1, -3, 0, -1, 0, 0, -1135, -620, -1, -1793, -1]
# pulled from "tactics_work/kalah-results-1-6-0-2-0.json" :
TDATA[(1, 6, 0, 2, 0)] = \
    [-810, -1, 0, -1, 0, 0, 3, -1, -3, 0, -5, 5, 1671, -1, 0, -1350, -353, -14]
# pulled from "tactics_work/kalah-results-1-6-0-2-1.json" :
TDATA[(1, 6, 0, 2, 1)] = \
    [-884, 1, -1, -2, -3, 0, 0, -1, 0, -1, 4, -1, -142, 920, -1368, 0, 0, -1926]
# pulled from "tactics_work/kalah-results-1-6-0-2-2.json" :
TDATA[(1, 6, 0, 2, 2)] = \
    [0, -294, 280, 501, -812, 0, -2, 0, 0, 1, 1, 1, 0, -1040, -891, 1157, 1, -262]
# pulled from "tactics_work/kalah-results-1-6-0-2-3.json" :
TDATA[(1, 6, 0, 2, 3)] = \
    [-1, -412, 0, 269, 361, -2616, 2, 0, 1, 1, 3, 0, 0, -1, 0, -1676, -4037, 253]
# pulled from "tactics_work/kalah-results-1-6-3-0-0.json" :
TDATA[(1, 6, 3, 0, 0)] = \
    [0, 0, 0, -1682, -1510, 552, 0, 2, -1, 0, 0, -2, -1768, 0, 0, -1629, 883, -1399]
# pulled from "tactics_work/kalah-results-1-6-3-0-1.json" :
TDATA[(1, 6, 3, 0, 1)] = \
    [1, 0, -19, 0, -1, -449, 5, 0, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-0-2.json" :
TDATA[(1, 6, 3, 0, 2)] = \
    [0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, -1, -1295, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-1-6-3-0-3.json" :
TDATA[(1, 6, 3, 0, 3)] = \
    [-278, -1557, 0, 1198, 0, 1, -1, 3, 1, 0, -2, 0, -268, -360, 0, 1167, -1, 0]
# pulled from "tactics_work/kalah-results-1-6-3-1-0.json" :
TDATA[(1, 6, 3, 1, 0)] = \
    [0, 1, -1, 0, 0, 0, 0, 0, 0, 0, -2, 4, -1, 0, 0, 109, -1, 371]
# pulled from "tactics_work/kalah-results-1-6-3-1-1.json" :
TDATA[(1, 6, 3, 1, 1)] = \
    [-217, 342, 664, 0, -1, 1, 0, 0, -1, 1, 0, -1, 0, -1, 1, -1252, -299, 0]
# pulled from "tactics_work/kalah-results-1-6-3-1-2.json" :
TDATA[(1, 6, 3, 1, 2)] = \
    [0, -852, 0, 0, 0, -1307, 0, 1, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-1-3.json" :
TDATA[(1, 6, 3, 1, 3)] = \
    [0, 0, -954, 0, 0, 0, 3, 0, 0, -3, -1, -1, -1, -1, 0, 0, -1998, -149]
# pulled from "tactics_work/kalah-results-1-6-3-2-0.json" :
TDATA[(1, 6, 3, 2, 0)] = \
    [-2, 2, -2932, 0, 0, 0, 1, 0, 0, 6, 0, -3, -1, -33, -493, 2, 1, -1]
# pulled from "tactics_work/kalah-results-1-6-3-2-1.json" :
TDATA[(1, 6, 3, 2, 1)] = \
    [0, -1, -1518, 1628, -3170, 150, 0, 1, 2, 0, -5, 0, 0, 0, -157, -798, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-2-2.json" :
TDATA[(1, 6, 3, 2, 2)] = \
    [-652, 0, 259, 1138, 1, 0, 0, 0, 0, 0, 0, 0, 1, -515, 0, 0, 2, -2]
# pulled from "tactics_work/kalah-results-1-6-3-2-3.json" :
TDATA[(1, 6, 3, 2, 3)] = \
    [-1499, 0, 1, 555, -1489, 1854, -3, -1, -1, 0, 0, -1, 0, 0, 373, 1565, 1814, 0]
# pulled from "tactics_work/kalah-results-2-4-0-0-0.json" :
TDATA[(2, 4, 0, 0, 0)] = \
    [0, 0, 0, 0, -437, 0, -2, 4, 0, 1, 4, 0, 0, 1, 0, -1035, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-0-0-1.json" :
TDATA[(2, 4, 0, 0, 1)] = \
    [-68, -1230, -1, -952, -2118, 0, -3, -3, -1, 3, -2, -1, 0, 1160, -1184, -1, -2501, 55]
# pulled from "tactics_work/kalah-results-2-4-0-0-2.json" :
TDATA[(2, 4, 0, 0, 2)] = \
    [242, -1810, -58, 1, -773, 1046, 3, 1, 1, 0, 0, 0, -2873, 0, 0, 0, -1441, 504]
# pulled from "tactics_work/kalah-results-2-4-0-0-3.json" :
TDATA[(2, 4, 0, 0, 3)] = \
    [0, 0, 1, 223, 0, -257, 2, 0, 0, 1, -1, 0, 0, -1, -1974, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-0-1-0.json" :
TDATA[(2, 4, 0, 1, 0)] = \
    [-330, -1249, 1, 1, 0, -1548, 0, 1, 0, 1, 0, 0, 0, 1670, 0, -3088, -138, 0]
# pulled from "tactics_work/kalah-results-2-4-0-1-1.json" :
TDATA[(2, 4, 0, 1, 1)] = \
    [1, 0, 0, -1245, 1704, 0, -5, 0, 0, 4, -1, -1, 391, 0, 0, 0, -844, 1]
# pulled from "tactics_work/kalah-results-2-4-0-1-2.json" :
TDATA[(2, 4, 0, 1, 2)] = \
    [-1375, 1, 0, 957, -1088, 0, 0, 0, 0, 1, 1, 0, -1, 0, -1093, -617, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-0-1-3.json" :
TDATA[(2, 4, 0, 1, 3)] = \
    [-2, 978, 1, 0, -821, -1, -3, 0, 0, -1, 0, 0, 588, -1181, -2445, -1, -1491, 0]
# pulled from "tactics_work/kalah-results-2-4-0-2-0.json" :
TDATA[(2, 4, 0, 2, 0)] = \
    [1080, 0, 1, 0, 0, -1234, 4, 0, -2, 1, -5, 0, -1326, 0, 0, -1, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-0-2-1.json" :
TDATA[(2, 4, 0, 2, 1)] = \
    [0, 1497, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, -910, -1151, 0, 1, 0, 1856]
# pulled from "tactics_work/kalah-results-2-4-0-2-2.json" :
TDATA[(2, 4, 0, 2, 2)] = \
    [0, 579, -1, 1, -1063, -1, 5, 0, -3, 0, 0, 0, 0, -1683, 0, 0, 0, 53]
# pulled from "tactics_work/kalah-results-2-4-0-2-3.json" :
TDATA[(2, 4, 0, 2, 3)] = \
    [1, 0, -1, 282, -1, 0, 0, 0, -2, 8, -1, 0, 1, -480, 0, -1, -647, 852]
# pulled from "tactics_work/kalah-results-2-4-3-0-0.json" :
TDATA[(2, 4, 3, 0, 0)] = \
    [-1917, 1, -2, 1729, -1592, 1078, 0, 0, 2, 0, 0, 0, 1099, -335, 0, 0, 931, 1429]
# pulled from "tactics_work/kalah-results-2-4-3-0-1.json" :
TDATA[(2, 4, 3, 0, 1)] = \
    [0, 1282, -864, 755, 1, -3385, -5, 0, 0, 0, -1, -1, 783, 1370, -1, 1472, 1402, 0]
# pulled from "tactics_work/kalah-results-2-4-3-0-2.json" :
TDATA[(2, 4, 3, 0, 2)] = \
    [0, 0, 1652, -1683, -1, 0, 2, 0, -1, 0, 4, 2, 1, 0, 0, 0, 0, 119]
# pulled from "tactics_work/kalah-results-2-4-3-0-3.json" :
TDATA[(2, 4, 3, 0, 3)] = \
    [1632, 1555, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1505, 0, 1, 0]
# pulled from "tactics_work/kalah-results-2-4-3-1-0.json" :
TDATA[(2, 4, 3, 1, 0)] = \
    [0, -367, 2446, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 1584, 0, 1067]
# pulled from "tactics_work/kalah-results-2-4-3-1-1.json" :
TDATA[(2, 4, 3, 1, 1)] = \
    [0, 0, 0, -1, -1715, 1016, 0, 0, 3, -1, 1, 0, 0, 1698, -2, -1, 0, 845]
# pulled from "tactics_work/kalah-results-2-4-3-1-2.json" :
TDATA[(2, 4, 3, 1, 2)] = \
    [0, 0, -459, -301, -1256, 0, 1, -3, 4, -1, 3, 0, -1, -1, 0, -1716, -994, 1960]
# pulled from "tactics_work/kalah-results-2-4-3-1-3.json" :
TDATA[(2, 4, 3, 1, 3)] = \
    [1, -2, 0, 515, -87, -1, 0, -3, 0, -3, 0, -1, 3, 0, 584, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-0.json" :
TDATA[(2, 4, 3, 2, 0)] = \
    [727, -1, 520, 0, -529, 0, -3, 0, -2, 1, -2, -4, 0, 1796, 0, 0, 0, -688]
# pulled from "tactics_work/kalah-results-2-4-3-2-1.json" :
TDATA[(2, 4, 3, 2, 1)] = \
    [-135, 0, 0, 81, -1, 1941, 0, 0, -1, 1, 8, 1, 676, 0, 0, 0, -234, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-2.json" :
TDATA[(2, 4, 3, 2, 2)] = \
    [-1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1155, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-3.json" :
TDATA[(2, 4, 3, 2, 3)] = \
    [-88, 0, -1255, -1105, 1751, 0, 1, 0, 0, 1, 2, 0, 1161, 1060, 710, 758, 1610, 1309]
# pulled from "tactics_work/kalah-results-2-3-0-0-0.json" :
TDATA[(2, 3, 0, 0, 0)] = \
    [-383, 0, -1779, 349, 254, -1917, 0, 0, 1, 0, 0, 0, 1145, 0, 0, -698, 749, 0]
# pulled from "tactics_work/kalah-results-2-3-0-0-1.json" :
TDATA[(2, 3, 0, 0, 1)] = \
    [2685, -356, 0, 1896, 0, 0, 1, 0, -1, 0, 0, -3, 1651, -2, -1940, 0, -372, 0]
# pulled from "tactics_work/kalah-results-2-3-0-0-2.json" :
TDATA[(2, 3, 0, 0, 2)] = \
    [0, 0, 0, 0, 0, 1434, 0, 0, 0, 0, 0, 0, 0, 0, 567, 1410, 0, -1995]
# pulled from "tactics_work/kalah-results-2-3-0-0-3.json" :
TDATA[(2, 3, 0, 0, 3)] = \
    [0, 0, -1007, 1198, 0, 0, -1, 2, 0, -3, -1, 0, -1, 0, -1, -790, 1872, 836]
# pulled from "tactics_work/kalah-results-2-3-0-1-0.json" :
TDATA[(2, 3, 0, 1, 0)] = \
    [1523, 0, 0, -959, 0, 1449, 0, 3, -1, 0, -1, -4, 0, -1, -1204, 292, 0, -2644]
# pulled from "tactics_work/kalah-results-2-3-0-1-1.json" :
TDATA[(2, 3, 0, 1, 1)] = \
    [-1986, 1, -360, 0, 1442, 1472, -1, 0, -5, 1, -3, -1, -938, 0, -1320, -1780, 825, -1]
# pulled from "tactics_work/kalah-results-2-3-0-1-2.json" :
TDATA[(2, 3, 0, 1, 2)] = \
    [-173, -1240, 0, 0, -1, 784, 0, 0, 0, 6, 1, 0, 0, -1, -3699, 0, 1430, 1]
# pulled from "tactics_work/kalah-results-2-3-0-1-3.json" :
TDATA[(2, 3, 0, 1, 3)] = \
    [-146, 0, 324, -1587, 1, 2736, 0, 1, -3, 2, 5, 3, 0, 2, 1347, 0, 1507, -1961]
# pulled from "tactics_work/kalah-results-2-3-0-2-0.json" :
TDATA[(2, 3, 0, 2, 0)] = \
    [0, 0, 0, 530, -1132, 0, 0, 0, -1, 1, -1, 1, 0, 100, 915, 0, 0, -1]
# pulled from "tactics_work/kalah-results-2-3-0-2-1.json" :
TDATA[(2, 3, 0, 2, 1)] = \
    [-217, 0, 755, 1, 0, 93, -2, 4, 1, -1, 0, 1, 0, 0, 1, 1378, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-0-2-2.json" :
TDATA[(2, 3, 0, 2, 2)] = \
    [0, 0, 0, 1, 0, -1, -3, 0, 0, 0, -1, 1, 0, 1, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-2-3-0-2-3.json" :
TDATA[(2, 3, 0, 2, 3)] = \
    [0, -1962, -2658, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 18, -1, 84, 1, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-0.json" :
TDATA[(2, 3, 3, 0, 0)] = \
    [-1, 0, 62, 0, 0, 1657, -1, 1, 0, 0, 0, -1, 172, -1616, 0, 2, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-1.json" :
TDATA[(2, 3, 3, 0, 1)] = \
    [-1807, 840, 0, 2005, 1, 1, -1, 0, -1, 0, -1, 3, -1, -332, -1, 2894, 0, 1676]
# pulled from "tactics_work/kalah-results-2-3-3-0-2.json" :
TDATA[(2, 3, 3, 0, 2)] = \
    [0, 0, 0, 1, -3030, 0, 0, 3, 0, 3, 0, 3, 0, 0, 0, 1, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-3.json" :
TDATA[(2, 3, 3, 0, 3)] = \
    [0, 0, 859, -1, 0, 0, 0, -1, 0, -1, -1, 3, -1092, 0, 0, 0, 0, 190]
# pulled from "tactics_work/kalah-results-2-3-3-1-0.json" :
TDATA[(2, 3, 3, 1, 0)] = \
    [-1653, 0, 0, -594, 0, 0, -2, 0, 0, 1, -1, -3, 0, 0, -1, -1242, -1, -2]
# pulled from "tactics_work/kalah-results-2-3-3-1-1.json" :
TDATA[(2, 3, 3, 1, 1)] = \
    [-1565, -248, 0, 0, 0, 0, 1, 0, -1, 0, 1, 0, 0, 0, 0, 0, -1, -853]
# pulled from "tactics_work/kalah-results-2-3-3-1-2.json" :
TDATA[(2, 3, 3, 1, 2)] = \
    [0, 0, 0, 0, 226, 1844, -1, 0, 3, 1, 0, 0, 1, 1698, -1625, -1232, -957, 1]
# pulled from "tactics_work/kalah-results-2-3-3-1-3.json" :
TDATA[(2, 3, 3, 1, 3)] = \
    [-1367, 3, -904, -283, 1, 797, 0, 0, 0, 1, -2, 1, 1211, -1232, 916, 0, -1429, -1]
# pulled from "tactics_work/kalah-results-2-3-3-2-0.json" :
TDATA[(2, 3, 3, 2, 0)] = \
    [-911, 1, -1978, 418, 0, 1041, 0, 2, 0, 0, 3, -1, -2588, 0, -881, -894, -1, -1]
# pulled from "tactics_work/kalah-results-2-3-3-2-1.json" :
TDATA[(2, 3, 3, 2, 1)] = \
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, -1, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-2-2.json" :
TDATA[(2, 3, 3, 2, 2)] = \
    [-1094, 0, -2, -192, 1274, 64, 0, 0, 1, 0, 0, 0, 0, -1, -13, 124, -621, 0]
# pulled from "tactics_work/kalah-results-2-3-3-2-3.json" :
TDATA[(2, 3, 3, 2, 3)] = \
    [0, 1, 1, 231, 0, -2, 0, 1, -2, -2, 0, 0, 1, 0, 1300, -1, 289, 513]
# pulled from "tactics_work/kalah-results-2-5-0-0-0.json" :
TDATA[(2, 5, 0, 0, 0)] = \
    [1, 0, 602, -1, -486, 1, -4, 2, 1, 5, 1, 0, 225, 1, 1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-0-0-1.json" :
TDATA[(2, 5, 0, 0, 1)] = \
    [0, 0, -864, 0, -1, 0, 0, -1, 0, 0, 0, 0, 0, -398, 0, 1, 501, 1113]
# pulled from "tactics_work/kalah-results-2-5-0-0-2.json" :
TDATA[(2, 5, 0, 0, 2)] = \
    [0, 1160, 0, -1, -323, 1, 0, 0, -1, 0, 0, 3, 0, 0, -509, -328, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-0-0-3.json" :
TDATA[(2, 5, 0, 0, 3)] = \
    [-2, -1, 0, 0, -796, -1573, 0, -5, 0, 0, 0, -2, 0, 1, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-2-5-0-1-0.json" :
TDATA[(2, 5, 0, 1, 0)] = \
    [2078, 0, -2, 0, -862, 796, 0, -1, 0, 0, 0, 0, 0, 1237, -1674, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-0-1-1.json" :
TDATA[(2, 5, 0, 1, 1)] = \
    [-92, -126, 1, -493, -1, 1828, 0, 0, -1, 1, 0, -2, 0, 1303, -1650, -1569, -1, 1]
# pulled from "tactics_work/kalah-results-2-5-0-1-2.json" :
TDATA[(2, 5, 0, 1, 2)] = \
    [0, -331, 0, 0, 1598, 0, -2, 0, 0, 0, 0, 0, 1492, -1, 0, -1356, 0, 1]
# pulled from "tactics_work/kalah-results-2-5-0-1-3.json" :
TDATA[(2, 5, 0, 1, 3)] = \
    [0, -67, 0, -2, 1264, 1119, -1, 1, 2, 2, 1, 3, -1036, 0, 166, -841, -1573, 0]
# pulled from "tactics_work/kalah-results-2-5-0-2-0.json" :
TDATA[(2, 5, 0, 2, 0)] = \
    [1, 979, 0, 0, 1621, 0, 0, 0, 5, 1, 0, 1, -2, 0, 0, 0, -603, 0]
# pulled from "tactics_work/kalah-results-2-5-0-2-1.json" :
TDATA[(2, 5, 0, 2, 1)] = \
    [1, 0, -776, 0, 0, -434, 5, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-0-2-2.json" :
TDATA[(2, 5, 0, 2, 2)] = \
    [0, -1, 0, 1306, -2, 1, 2, 3, 0, -2, 0, -1, 0, 1, 2053, 0, -1, 1]
# pulled from "tactics_work/kalah-results-2-5-0-2-3.json" :
TDATA[(2, 5, 0, 2, 3)] = \
    [0, -1, -1699, 492, 1, 0, -3, 0, 0, 3, 0, 0, 0, 0, 0, 0, -1775, 0]
# pulled from "tactics_work/kalah-results-2-5-3-0-0.json" :
TDATA[(2, 5, 3, 0, 0)] = \
    [1752, -651, -1375, 0, 0, 0, 0, 0, -4, 0, 0, 0, -1, 1, 0, 0, -1582, -1]
# pulled from "tactics_work/kalah-results-2-5-3-0-1.json" :
TDATA[(2, 5, 3, 0, 1)] = \
    [0, -819, -163, 0, 1136, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 1080, 1055, 1]
# pulled from "tactics_work/kalah-results-2-5-3-0-2.json" :
TDATA[(2, 5, 3, 0, 2)] = \
    [-700, 0, 0, 1, 1863, 0, 0, -4, -1, -1, -1, 0, 1, 0, 1419, 0, 0, -889]
# pulled from "tactics_work/kalah-results-2-5-3-0-3.json" :
TDATA[(2, 5, 3, 0, 3)] = \
    [-658, -1258, 1006, 0, -695, 683, -1, 0, 0, 0, -1, 4, 0, 1023, 0, 475, 2, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-0.json" :
TDATA[(2, 5, 3, 1, 0)] = \
    [0, 0, 0, 0, -1, 0, -1, -1, -2, 0, 0, -2, 0, 0, 0, 0, 1437, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-1.json" :
TDATA[(2, 5, 3, 1, 1)] = \
    [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, -1, 0, 0, 0, -895, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-2.json" :
TDATA[(2, 5, 3, 1, 2)] = \
    [-1, 1, -450, 0, 0, 0, 0, 0, 0, 1, 2, 0, -364, -1, -1, 1870, -55, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-3.json" :
TDATA[(2, 5, 3, 1, 3)] = \
    [-107, 0, 0, 0, -2, 0, 1, -1, 0, -4, 1, -3, 1737, 910, 1, -1, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-3-2-0.json" :
TDATA[(2, 5, 3, 2, 0)] = \
    [0, 0, 0, 0, 0, 330, 1, 0, 0, -1, 0, 0, 1340, 0, 0, -130, 0, 1]
# pulled from "tactics_work/kalah-results-2-5-3-2-1.json" :
TDATA[(2, 5, 3, 2, 1)] = \
    [0, 0, 289, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-3-2-2.json" :
TDATA[(2, 5, 3, 2, 2)] = \
    [-716, -2, -1091, 1676, 0, 2, 4, 0, 0, 1, 4, -7, 0, -952, 1578, -1, -1039, -73]
# pulled from "tactics_work/kalah-results-2-5-3-2-3.json" :
TDATA[(2, 5, 3, 2, 3)] = \
    [718, -1887, 1, 546, -2, 1, 8, 0, -3, 0, 2, 3, 0, -1320, 0, 0, 3476, -1357]
# pulled from "tactics_work/kalah-results-2-6-0-0-0.json" :
TDATA[(2, 6, 0, 0, 0)] = \
    [0, 0, 0, -1, 0, -1569, 0, 0, 0, 1, 2, -3, 1, -352, 504, 1143, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-0-0-1.json" :
TDATA[(2, 6, 0, 0, 1)] = \
    [-4, 1069, -1, 1, 0, 2948, 0, -3, 2, -3, 8, 0, 0, -302, 0, 0, 0, -1962]
# pulled from "tactics_work/kalah-results-2-6-0-0-2.json" :
TDATA[(2, 6, 0, 0, 2)] = \
    [-829, 0, 1284, 0, -1, -777, 1, -1, 1, 2, 6, 1, -1, 1, 442, 2, -56, -2]
# pulled from "tactics_work/kalah-results-2-6-0-0-3.json" :
TDATA[(2, 6, 0, 0, 3)] = \
    [-1, 1424, -1, 0, 0, 0, 0, 0, -1, 0, 2, 0, 0, 2584, 0, -1758, -1, 1]
# pulled from "tactics_work/kalah-results-2-6-0-1-0.json" :
TDATA[(2, 6, 0, 1, 0)] = \
    [-659, 1912, 862, -550, 0, 0, 1, 0, 0, 0, 0, 0, -1177, -92, -1736, 0, 0, 1694]
# pulled from "tactics_work/kalah-results-2-6-0-1-1.json" :
TDATA[(2, 6, 0, 1, 1)] = \
    [1, -892, 0, 1520, -1, 1216, 0, 2, 0, 4, 2, 0, -575, -1, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-0-1-2.json" :
TDATA[(2, 6, 0, 1, 2)] = \
    [0, 0, 1641, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, -1165, 2, -2734, -1813, -1444]
# pulled from "tactics_work/kalah-results-2-6-0-1-3.json" :
TDATA[(2, 6, 0, 1, 3)] = \
    [1747, -1, 1, -639, 649, 0, 0, 0, -1, 6, 0, 0, -1706, 0, 100, 1, 1091, -1]
# pulled from "tactics_work/kalah-results-2-6-0-2-0.json" :
TDATA[(2, 6, 0, 2, 0)] = \
    [1, 1015, 1, 900, 0, -3, -1, -1, -1, -2, -3, -2, 1472, -1587, -1915, 109, -1122, 0]
# pulled from "tactics_work/kalah-results-2-6-0-2-1.json" :
TDATA[(2, 6, 0, 2, 1)] = \
    [0, 0, -207, 0, 0, 0, -1, -2, 1, -2, 0, -1, 0, 1, -1, -1322, -1, -1068]
# pulled from "tactics_work/kalah-results-2-6-0-2-2.json" :
TDATA[(2, 6, 0, 2, 2)] = \
    [1153, -2198, 0, 1, 0, 0, -1, 0, 0, 2, 3, -4, -1, -918, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-0-2-3.json" :
TDATA[(2, 6, 0, 2, 3)] = \
    [-186, -1, -431, -413, 668, -995, 0, 0, -1, 0, -4, 0, 0, 1, -1918, 0, -1, -1065]
# pulled from "tactics_work/kalah-results-2-6-3-0-0.json" :
TDATA[(2, 6, 3, 0, 0)] = \
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 1, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-0-1.json" :
TDATA[(2, 6, 3, 0, 1)] = \
    [-1, 0, -1131, 870, 1628, 1153, 2, 0, 0, -3, 1, -1, 0, 0, 0, 0, 1, 1112]
# pulled from "tactics_work/kalah-results-2-6-3-0-2.json" :
TDATA[(2, 6, 3, 0, 2)] = \
    [0, 430, 0, 1, 1, 0, 0, 0, 0, -1, 0, 0, 0, -1, 1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-0-3.json" :
TDATA[(2, 6, 3, 0, 3)] = \
    [0, 0, -1, 1, 859, -1, 0, 3, 0, -1, 0, -6, -218, -1, 0, 0, -2, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-0.json" :
TDATA[(2, 6, 3, 1, 0)] = \
    [0, -320, -163, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-1.json" :
TDATA[(2, 6, 3, 1, 1)] = \
    [2, 0, -1760, -1996, -816, 917, 1, 0, -1, 2, 0, 1, 350, 1, 0, 1, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-2.json" :
TDATA[(2, 6, 3, 1, 2)] = \
    [485, 1, -322, 0, 0, 799, 0, 0, -1, 1, -1, 1, 1, 0, -1028, 334, -631, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-3.json" :
TDATA[(2, 6, 3, 1, 3)] = \
    [-150, 414, 0, 0, 0, 0, 0, 0, -3, 3, 0, -2, 0, 1, 0, 1, 548, 0]
# pulled from "tactics_work/kalah-results-2-6-3-2-0.json" :
TDATA[(2, 6, 3, 2, 0)] = \
    [1910, 1, 0, -490, -1062, 0, 0, 1, -1, 1, 0, -2, 1, 1934, 0, 374, 666, -15]
# pulled from "tactics_work/kalah-results-2-6-3-2-1.json" :
TDATA[(2, 6, 3, 2, 1)] = \
    [-1, 1002, 0, 0, 0, -516, -3, 2, -1, 1, 0, -1, 0, -278, -2792, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-2-2.json" :
TDATA[(2, 6, 3, 2, 2)] = \
    [0, 0, 0, -1521, 0, 1907, 0, -2, -4, -1, 0, 0, 503, 0, 1997, 1108, 1894, 0]
# pulled from "tactics_work/kalah-results-2-6-3-2-3.json" :
TDATA[(2, 6, 3, 2, 3)] = \
    [0, 0, 0, -919, 1223, 1, 1, -2, 0, 0, -1, 2, 278, 166, 1, -1986, 1956, 1]

# DO NOT EDIT: autogenerated by "apply_tactics_generated.py"
