# DO NOT EDIT: autogenerated by "apply_tactics_generated.py"

TDATA = {}
# pulled from "tactics_work/kalah-results-1-4-1-0-0.json" :
TDATA[(1, 4, 1, 0, 0)] = \
    [1, 2, 714, 0, 1304, 1065, 2, 0, 0, 2, 0, 804, 672, 851, 0, 0, 0, 1]
# pulled from "tactics_work/kalah-results-1-4-1-0-1.json" :
TDATA[(1, 4, 1, 0, 1)] = \
    [202, 3473, 0, 1, 835, 0, 2, 1, 0, 2, 275, 588, 0, 369, 777, 1, 600, 1086]
# pulled from "tactics_work/kalah-results-1-4-1-0-2.json" :
TDATA[(1, 4, 1, 0, 2)] = \
    [2, 2, 0, 1, 1201, 0, 1, 1, 668, 1, 3, 995, 0, 1, 15, 0, 0, 965]
# pulled from "tactics_work/kalah-results-1-4-1-0-3.json" :
TDATA[(1, 4, 1, 0, 3)] = \
    [2040, 1793, 0, 1241, 227, 4, 408, 155, 568, 0, 1, 657, 0, 1, 0, 0, 1233, 674]
# pulled from "tactics_work/kalah-results-1-4-1-1-0.json" :
TDATA[(1, 4, 1, 1, 0)] = \
    [1, 1473, 0, 0, 1567, 2, 533, 759, 619, 0, 0, 2348, 547, 0, 230, 0, 2, 747]
# pulled from "tactics_work/kalah-results-1-4-1-1-1.json" :
TDATA[(1, 4, 1, 1, 1)] = \
    [1002, 2046, 1, 341, 0, 2, 1, 2, 0, 0, 0, 0, 3, 283, 3, 0, 0, 2030]
# pulled from "tactics_work/kalah-results-1-4-1-1-2.json" :
TDATA[(1, 4, 1, 1, 2)] = \
    [146, 1816, 1049, 2101, 641, 248, 2, 79, 339, 661, 0, 1357, 602, 1, 380, 415, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-1-1-3.json" :
TDATA[(1, 4, 1, 1, 3)] = \
    [600, 830, 823, 0, 0, 333, 296, 740, 453, 1, 547, 1558, 1, 850, 0, 0, 0, 2]
# pulled from "tactics_work/kalah-results-1-4-1-2-0.json" :
TDATA[(1, 4, 1, 2, 0)] = \
    [2, 949, 380, 0, 0, 390, 1156, 1, 2, 1, 2, 2447, 0, 0, 983, 0, 550, 2]
# pulled from "tactics_work/kalah-results-1-4-1-2-1.json" :
TDATA[(1, 4, 1, 2, 1)] = \
    [939, 1170, 2, 0, 0, 546, 2, 0, 1, 1, 2, 581, 0, 0, 0, 2, 0, 2]
# pulled from "tactics_work/kalah-results-1-4-1-2-2.json" :
TDATA[(1, 4, 1, 2, 2)] = \
    [842, 0, 135, 1486, 1513, 2, 634, 423, 334, 1, 310, 1974, 123, 527, 0, 1, 356, 0]
# pulled from "tactics_work/kalah-results-1-4-1-2-3.json" :
TDATA[(1, 4, 1, 2, 3)] = \
    [2, 0, 273, 191, 0, 1051, 1, 317, 698, 0, 4, 965, 791, 0, 1, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-2-0-0.json" :
TDATA[(1, 4, 2, 0, 0)] = \
    [0, 1, 490, 1, 2, 1, 588, 0, 1, 0, 580, 1, 1, 1, 1, 1, 2, 1]
# pulled from "tactics_work/kalah-results-1-4-2-0-1.json" :
TDATA[(1, 4, 2, 0, 1)] = \
    [327, 110, 859, 0, 3, 485, 1, 2, 0, 1, 1, 0, 867, 2, 1, 0, 1, 1]
# pulled from "tactics_work/kalah-results-1-4-2-0-2.json" :
TDATA[(1, 4, 2, 0, 2)] = \
    [1, 87, 431, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 1, 0, 248, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-2-0-3.json" :
TDATA[(1, 4, 2, 0, 3)] = \
    [0, 0, 664, 1, 1, 354, 1, 1, 1, 1, 2, 1, 1393, 0, 238, 1, 0, 1]
# pulled from "tactics_work/kalah-results-1-4-2-1-0.json" :
TDATA[(1, 4, 2, 1, 0)] = \
    [1, 1, 1283, 1, 236, 1, 1, 1, 2, 1, 1, 1, 1271, 2, 0, 1, 2, 0]
# pulled from "tactics_work/kalah-results-1-4-2-1-1.json" :
TDATA[(1, 4, 2, 1, 1)] = \
    [546, 908, 1, 1, 2, 1, 2, 1, 1, 1, 0, 315, 875, 1, 1, 755, 820, 1]
# pulled from "tactics_work/kalah-results-1-4-2-1-2.json" :
TDATA[(1, 4, 2, 1, 2)] = \
    [0, 2, 805, 0, 1394, 1716, 550, 175, 1, 1, 2, 0, 302, 1124, 390, 861, 238, 1]
# pulled from "tactics_work/kalah-results-1-4-2-1-3.json" :
TDATA[(1, 4, 2, 1, 3)] = \
    [20, 0, 1, 1, 1, 1, 416, 387, 1, 1, 1, 1, 0, 1, 1, 0, 166, 1]
# pulled from "tactics_work/kalah-results-1-4-2-2-0.json" :
TDATA[(1, 4, 2, 2, 0)] = \
    [0, 0, 2, 0, 1, 873, 2, 61, 1, 0, 755, 0, 1, 1, 838, 1142, 907, 1]
# pulled from "tactics_work/kalah-results-1-4-2-2-1.json" :
TDATA[(1, 4, 2, 2, 1)] = \
    [2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-4-2-2-2.json" :
TDATA[(1, 4, 2, 2, 2)] = \
    [2, 0, 1, 2, 1, 377, 0, 1, 2, 2, 1, 0, 811, 1, 1, 1001, 2, 1]
# pulled from "tactics_work/kalah-results-1-4-2-2-3.json" :
TDATA[(1, 4, 2, 2, 3)] = \
    [261, 1, 1, 1003, 1359, 1, 0, 0, 1, 1, 1, 701, 2, 0, 0, 2, 3, 72]
# pulled from "tactics_work/kalah-results-1-4-3-0-0.json" :
TDATA[(1, 4, 3, 0, 0)] = \
    [0, 0, 1355, 705, 2, 139, 2514, 3259, 873, 682, 3150, 2, 351, 2328, 1691, 727, 50, 726]
# pulled from "tactics_work/kalah-results-1-4-3-0-1.json" :
TDATA[(1, 4, 3, 0, 1)] = \
    [6115, 1, 163, 6675, 1471, 2, 0, 2, 0, 5, 1, 2, 2, 0, 2, 0, 339, 2063]
# pulled from "tactics_work/kalah-results-1-4-3-0-2.json" :
TDATA[(1, 4, 3, 0, 2)] = \
    [3573, 1531, 6359, 1440, 1920, 2, 6, 8, 14, 8, 1, 3, 4995, 676, 2426, 2, 3689, 1278]
# pulled from "tactics_work/kalah-results-1-4-3-0-3.json" :
TDATA[(1, 4, 3, 0, 3)] = \
    [2238, 2892, 0, 3270, 1842, 8361, 1, 6, 0, 11, 4, 0, 3685, 1728, 1, 0, 0, 3708]
# pulled from "tactics_work/kalah-results-1-4-3-1-0.json" :
TDATA[(1, 4, 3, 1, 0)] = \
    [258, 3118, 1812, 2623, 3305, 3387, 6, 0, 6, 1, 3, 10, 0, 4479, 3568, 3, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-1.json" :
TDATA[(1, 4, 3, 1, 1)] = \
    [5405, 4050, 3616, 2016, 815, 2308, 1, 6, 4, 13, 0, 20, 4167, 0, 1290, 167, 47, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-2.json" :
TDATA[(1, 4, 3, 1, 2)] = \
    [3359, 2321, 2030, 2261, 1950, 176, 4, 0, 2, 3, 1, 4, 2, 221, 466, 1, 4270, 1886]
# pulled from "tactics_work/kalah-results-1-4-3-1-3.json" :
TDATA[(1, 4, 3, 1, 3)] = \
    [7679, 1171, 812, 4090, 3492, 552, 7, 7, 5, 1, 8, 0, 2260, 0, 3, 2046, 1046, 502]
# pulled from "tactics_work/kalah-results-1-4-3-2-0.json" :
TDATA[(1, 4, 3, 2, 0)] = \
    [1, 5468, 0, 2257, 0, 1836, 4, 8, 5, 6, 6, 7, 2701, 5617, 0, 0, 1, 1147]
# pulled from "tactics_work/kalah-results-1-4-3-2-1.json" :
TDATA[(1, 4, 3, 2, 1)] = \
    [6553, 7270, 2553, 3416, 778, 4542, 3, 0, 0, 5, 5, 1, 553, 1056, 2265, 1148, 4396, 7361]
# pulled from "tactics_work/kalah-results-1-4-3-2-2.json" :
TDATA[(1, 4, 3, 2, 2)] = \
    [2910, 651, 2, 1, 1, 2729, 7, 0, 1, 5, 10, 5, 1405, 7398, 2362, 2294, 3447, 438]
# pulled from "tactics_work/kalah-results-1-4-3-2-3.json" :
TDATA[(1, 4, 3, 2, 3)] = \
    [2602, 0, 493, 5115, 1351, 1590, 3, 0, 2, 3, 0, 2, 2, 626, 5721, 1, 3458, 6091]
# pulled from "tactics_work/kalah-results-1-4-4-0-0.json" :
TDATA[(1, 4, 4, 0, 0)] = \
    [540, 2, 0, 1, 0, 1833, 1, 2, 0, 2, 0, 2, 2, 1, 1, 1, 1118, 1]
# pulled from "tactics_work/kalah-results-1-4-4-0-1.json" :
TDATA[(1, 4, 4, 0, 1)] = \
    [2, 1337, 1185, 376, 1, 3017, 1, 0, 1, 1, 1, 2, 1584, 2, 215, 0, 1, 1918]
# pulled from "tactics_work/kalah-results-1-4-4-0-2.json" :
TDATA[(1, 4, 4, 0, 2)] = \
    [1, 1, 1431, 1910, 0, 1636, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1478, 1]
# pulled from "tactics_work/kalah-results-1-4-4-0-3.json" :
TDATA[(1, 4, 4, 0, 3)] = \
    [1, 1572, 3419, 0, 0, 0, 1, 0, 8, 2, 1, 1, 1271, 1, 1, 0, 3, 2]
# pulled from "tactics_work/kalah-results-1-4-4-1-0.json" :
TDATA[(1, 4, 4, 1, 0)] = \
    [1, 1, 1, 1, 1, 2, 2, 0, 4, 3, 1, 1, 1059, 745, 1, 0, 2, 0]
# pulled from "tactics_work/kalah-results-1-4-4-1-1.json" :
TDATA[(1, 4, 4, 1, 1)] = \
    [1294, 1, 1, 1, 1192, 1, 2, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-4-1-2.json" :
TDATA[(1, 4, 4, 1, 2)] = \
    [1, 2, 0, 1553, 0, 199, 2, 1, 4, 2, 2, 1, 1166, 0, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-4-1-3.json" :
TDATA[(1, 4, 4, 1, 3)] = \
    [0, 207, 1716, 1, 0, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-4-4-2-0.json" :
TDATA[(1, 4, 4, 2, 0)] = \
    [1, 1852, 1, 2, 926, 1220, 1, 5, 0, 0, 0, 0, 1, 2, 1, 1, 1, 0]
# pulled from "tactics_work/kalah-results-1-4-4-2-1.json" :
TDATA[(1, 4, 4, 2, 1)] = \
    [1716, 34, 1433, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 483, 1, 0, 1414]
# pulled from "tactics_work/kalah-results-1-4-4-2-2.json" :
TDATA[(1, 4, 4, 2, 2)] = \
    [2, 1, 0, 1, 499, 1022, 0, 3, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-4-4-2-3.json" :
TDATA[(1, 4, 4, 2, 3)] = \
    [1, 213, 0, 1, 3, 1403, 2, 1, 5, 0, 1, 0, 1, 1, 0, 2, 1, 1956]
# pulled from "tactics_work/kalah-results-1-3-1-0-0.json" :
TDATA[(1, 3, 1, 0, 0)] = \
    [1830, 2, 1086, 0, 574, 584, 1776, 817, 0, 0, 2445, 0, 336, 1812, 636, 261, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-1-0-1.json" :
TDATA[(1, 3, 1, 0, 1)] = \
    [0, 2, 1, 1, 1, 2, 277, 0, 0, 1, 1, 0, 690, 145, 838, 1, 113, 2]
# pulled from "tactics_work/kalah-results-1-3-1-0-2.json" :
TDATA[(1, 3, 1, 0, 2)] = \
    [1344, 0, 517, 0, 750, 2, 218, 0, 0, 40, 841, 594, 413, 719, 717, 1520, 768, 216]
# pulled from "tactics_work/kalah-results-1-3-1-0-3.json" :
TDATA[(1, 3, 1, 0, 3)] = \
    [0, 700, 1476, 0, 0, 1840, 480, 2, 159, 275, 129, 839, 1, 1938, 0, 627, 0, 1]
# pulled from "tactics_work/kalah-results-1-3-1-1-0.json" :
TDATA[(1, 3, 1, 1, 0)] = \
    [0, 566, 2, 2, 973, 0, 2, 627, 0, 608, 1367, 2, 82, 0, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-1-1-1.json" :
TDATA[(1, 3, 1, 1, 1)] = \
    [0, 2, 649, 2, 2, 1, 153, 0, 1, 0, 2, 880, 0, 1, 2, 852, 2, 850]
# pulled from "tactics_work/kalah-results-1-3-1-1-2.json" :
TDATA[(1, 3, 1, 1, 2)] = \
    [572, 23, 392, 1, 780, 0, 123, 727, 1, 275, 1407, 0, 604, 850, 1089, 1, 23, 435]
# pulled from "tactics_work/kalah-results-1-3-1-1-3.json" :
TDATA[(1, 3, 1, 1, 3)] = \
    [0, 1509, 0, 1944, 0, 164, 604, 327, 0, 1, 1381, 0, 3, 392, 0, 3, 0, 2]
# pulled from "tactics_work/kalah-results-1-3-1-2-0.json" :
TDATA[(1, 3, 1, 2, 0)] = \
    [953, 258, 726, 782, 1, 2668, 2594, 0, 0, 0, 815, 569, 2, 439, 1159, 0, 2, 0]
# pulled from "tactics_work/kalah-results-1-3-1-2-1.json" :
TDATA[(1, 3, 1, 2, 1)] = \
    [1, 2, 67, 1647, 4, 1, 0, 1, 1, 1070, 2466, 1, 0, 275, 497, 122, 482, 656]
# pulled from "tactics_work/kalah-results-1-3-1-2-2.json" :
TDATA[(1, 3, 1, 2, 2)] = \
    [0, 1796, 3, 2, 344, 1, 1956, 293, 857, 1299, 3, 1691, 839, 1065, 1, 0, 1580, 0]
# pulled from "tactics_work/kalah-results-1-3-1-2-3.json" :
TDATA[(1, 3, 1, 2, 3)] = \
    [1148, 80, 1737, 0, 1244, 635, 727, 4, 799, 2537, 538, 2647, 225, 1464, 0, 1186, 2, 747]
# pulled from "tactics_work/kalah-results-1-3-2-0-0.json" :
TDATA[(1, 3, 2, 0, 0)] = \
    [0, 0, 881, 1, 0, 2, 1, 2, 534, 0, 1, 805, 1, 0, 0, 0, 1108, 0]
# pulled from "tactics_work/kalah-results-1-3-2-0-1.json" :
TDATA[(1, 3, 2, 0, 1)] = \
    [3, 1, 227, 1, 1028, 1, 1, 1, 1, 2, 0, 2, 1637, 2, 0, 1, 0, 1]
# pulled from "tactics_work/kalah-results-1-3-2-0-2.json" :
TDATA[(1, 3, 2, 0, 2)] = \
    [0, 2, 1, 538, 1, 1, 304, 0, 3, 0, 1, 1, 1, 0, 614, 726, 635, 1381]
# pulled from "tactics_work/kalah-results-1-3-2-0-3.json" :
TDATA[(1, 3, 2, 0, 3)] = \
    [0, 1, 2, 214, 1157, 1299, 90, 0, 2, 531, 2, 296, 823, 1, 0, 0, 730, 1]
# pulled from "tactics_work/kalah-results-1-3-2-1-0.json" :
TDATA[(1, 3, 2, 1, 0)] = \
    [0, 0, 54, 1, 1, 7, 2, 0, 2, 310, 343, 574, 0, 478, 1, 1, 1, 465]
# pulled from "tactics_work/kalah-results-1-3-2-1-1.json" :
TDATA[(1, 3, 2, 1, 1)] = \
    [1, 341, 1, 1, 4, 1, 2, 0, 2, 0, 3, 373, 0, 1, 1, 1, 1, 287]
# pulled from "tactics_work/kalah-results-1-3-2-1-2.json" :
TDATA[(1, 3, 2, 1, 2)] = \
    [965, 1, 1, 1, 1, 1, 696, 2, 0, 1, 1, 0, 450, 1, 171, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-3-2-1-3.json" :
TDATA[(1, 3, 2, 1, 3)] = \
    [1, 1, 2, 1, 540, 1, 915, 1, 1, 1, 1, 1, 1, 1, 1163, 347, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-2-2-0.json" :
TDATA[(1, 3, 2, 2, 0)] = \
    [2, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0, 201, 65, 312, 1, 1, 694, 1]
# pulled from "tactics_work/kalah-results-1-3-2-2-1.json" :
TDATA[(1, 3, 2, 2, 1)] = \
    [3, 894, 1, 2, 1, 340, 309, 1, 441, 2, 1, 266, 0, 117, 3, 1887, 162, 289]
# pulled from "tactics_work/kalah-results-1-3-2-2-2.json" :
TDATA[(1, 3, 2, 2, 2)] = \
    [2, 694, 1, 1, 2, 119, 1, 2, 1, 1, 636, 290, 102, 757, 0, 1, 70, 1283]
# pulled from "tactics_work/kalah-results-1-3-2-2-3.json" :
TDATA[(1, 3, 2, 2, 3)] = \
    [1, 2, 1, 0, 929, 753, 0, 1, 60, 1, 3, 1284, 0, 1, 1, 623, 0, 2]
# pulled from "tactics_work/kalah-results-1-3-3-0-0.json" :
TDATA[(1, 3, 3, 0, 0)] = \
    [0, 3326, 183, 3510, 460, 1647, 3, 6, 4, 1, 1, 2, 7712, 2384, 4877, 1, 0, 2589]
# pulled from "tactics_work/kalah-results-1-3-3-0-1.json" :
TDATA[(1, 3, 3, 0, 1)] = \
    [1, 5124, 0, 2, 979, 2570, 1, 7, 5, 2, 0, 1, 2968, 2, 726, 1769, 839, 3]
# pulled from "tactics_work/kalah-results-1-3-3-0-2.json" :
TDATA[(1, 3, 3, 0, 2)] = \
    [1487, 3636, 0, 1112, 340, 0, 7, 0, 6, 1, 7, 0, 1451, 1, 0, 1928, 2, 281]
# pulled from "tactics_work/kalah-results-1-3-3-0-3.json" :
TDATA[(1, 3, 3, 0, 3)] = \
    [1427, 5373, 1649, 888, 0, 0, 2, 1, 0, 7, 4, 4, 1573, 2, 611, 754, 533, 920]
# pulled from "tactics_work/kalah-results-1-3-3-1-0.json" :
TDATA[(1, 3, 3, 1, 0)] = \
    [0, 1222, 1232, 2265, 0, 3, 0, 3, 0, 3, 1, 5, 1807, 2755, 1242, 0, 0, 1150]
# pulled from "tactics_work/kalah-results-1-3-3-1-1.json" :
TDATA[(1, 3, 3, 1, 1)] = \
    [0, 2547, 0, 1878, 1213, 1316, 0, 6, 0, 0, 5, 3, 2, 4077, 5204, 5727, 435, 443]
# pulled from "tactics_work/kalah-results-1-3-3-1-2.json" :
TDATA[(1, 3, 3, 1, 2)] = \
    [0, 4181, 1002, 2728, 0, 1343, 4, 3, 2, 2, 3, 0, 2014, 1028, 2960, 673, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-3-1-3.json" :
TDATA[(1, 3, 3, 1, 3)] = \
    [0, 3133, 1873, 1919, 2734, 1136, 4, 1, 4, 4, 3, 2, 3704, 1, 2, 566, 2, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-0.json" :
TDATA[(1, 3, 3, 2, 0)] = \
    [1, 0, 2, 2493, 3849, 2172, 9, 3, 3, 1, 7, 10, 1746, 1265, 3702, 0, 183, 387]
# pulled from "tactics_work/kalah-results-1-3-3-2-1.json" :
TDATA[(1, 3, 3, 2, 1)] = \
    [1, 5, 706, 2, 2, 0, 0, 2, 0, 2, 6, 0, 180, 1989, 885, 2624, 3, 3436]
# pulled from "tactics_work/kalah-results-1-3-3-2-2.json" :
TDATA[(1, 3, 3, 2, 2)] = \
    [643, 1446, 2802, 0, 503, 1035, 1, 6, 0, 2, 1, 4, 0, 0, 1834, 4417, 1737, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-3.json" :
TDATA[(1, 3, 3, 2, 3)] = \
    [1071, 0, 3118, 2, 2, 947, 6, 3, 1, 1, 7, 3, 1319, 0, 589, 3208, 3, 1286]
# pulled from "tactics_work/kalah-results-1-3-4-0-0.json" :
TDATA[(1, 3, 4, 0, 0)] = \
    [149, 1, 3, 1672, 1179, 2, 1, 1, 1, 1, 1, 0, 229, 2, 0, 1, 1521, 1971]
# pulled from "tactics_work/kalah-results-1-3-4-0-1.json" :
TDATA[(1, 3, 4, 0, 1)] = \
    [2, 3, 699, 1, 1619, 1787, 1, 1, 2, 0, 2, 2, 1, 1911, 0, 744, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-4-0-2.json" :
TDATA[(1, 3, 4, 0, 2)] = \
    [1, 237, 1, 1723, 1610, 2, 2, 0, 0, 4, 1, 2, 1870, 0, 1285, 1899, 2, 0]
# pulled from "tactics_work/kalah-results-1-3-4-0-3.json" :
TDATA[(1, 3, 4, 0, 3)] = \
    [0, 0, 2418, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1302, 1, 0, 793, 1, 1]
# pulled from "tactics_work/kalah-results-1-3-4-1-0.json" :
TDATA[(1, 3, 4, 1, 0)] = \
    [0, 1279, 1, 1215, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1439, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-3-4-1-1.json" :
TDATA[(1, 3, 4, 1, 1)] = \
    [0, 3000, 2605, 1, 2, 0, 1, 1, 3, 1, 2, 1, 0, 2, 0, 0, 1, 1]
# pulled from "tactics_work/kalah-results-1-3-4-1-2.json" :
TDATA[(1, 3, 4, 1, 2)] = \
    [0, 0, 1, 61, 1124, 1, 1, 3, 1, 1, 5, 1, 0, 1812, 1235, 1, 1706, 828]
# pulled from "tactics_work/kalah-results-1-3-4-1-3.json" :
TDATA[(1, 3, 4, 1, 3)] = \
    [1, 2, 1, 1, 1216, 3399, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1108, 0]
# pulled from "tactics_work/kalah-results-1-3-4-2-0.json" :
TDATA[(1, 3, 4, 2, 0)] = \
    [1, 2136, 1837, 1, 1, 0, 0, 1, 1, 2, 4, 2, 1, 0, 455, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-3-4-2-1.json" :
TDATA[(1, 3, 4, 2, 1)] = \
    [1, 0, 1, 1483, 1181, 1556, 0, 0, 1, 1, 1, 5, 0, 3969, 1241, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-4-2-2.json" :
TDATA[(1, 3, 4, 2, 2)] = \
    [2, 2884, 0, 0, 863, 1613, 0, 1, 1, 4, 1, 0, 0, 701, 1135, 1, 1572, 0]
# pulled from "tactics_work/kalah-results-1-3-4-2-3.json" :
TDATA[(1, 3, 4, 2, 3)] = \
    [1, 1, 520, 1487, 1986, 1515, 1, 1, 4, 1, 0, 2, 11, 0, 2, 1887, 0, 1396]
# pulled from "tactics_work/kalah-results-1-5-1-0-0.json" :
TDATA[(1, 5, 1, 0, 0)] = \
    [944, 0, 154, 1, 528, 0, 4397, 1011, 0, 2, 506, 2, 779, 1948, 3, 0, 0, 611]
# pulled from "tactics_work/kalah-results-1-5-1-0-1.json" :
TDATA[(1, 5, 1, 0, 1)] = \
    [197, 1273, 0, 1, 2, 2, 921, 2, 709, 0, 0, 2383, 325, 1030, 1039, 125, 1404, 1552]
# pulled from "tactics_work/kalah-results-1-5-1-0-2.json" :
TDATA[(1, 5, 1, 0, 2)] = \
    [0, 825, 123, 536, 0, 0, 1747, 1, 0, 1, 0, 2669, 659, 1418, 596, 2, 2, 1]
# pulled from "tactics_work/kalah-results-1-5-1-0-3.json" :
TDATA[(1, 5, 1, 0, 3)] = \
    [639, 0, 158, 489, 772, 656, 672, 161, 0, 0, 2, 3486, 2, 0, 2, 2, 11, 22]
# pulled from "tactics_work/kalah-results-1-5-1-1-0.json" :
TDATA[(1, 5, 1, 1, 0)] = \
    [0, 0, 1, 0, 677, 0, 0, 0, 958, 360, 1, 1638, 125, 0, 0, 293, 120, 2]
# pulled from "tactics_work/kalah-results-1-5-1-1-1.json" :
TDATA[(1, 5, 1, 1, 1)] = \
    [438, 0, 1221, 1, 1124, 781, 1404, 759, 1, 2, 268, 577, 2, 2340, 201, 1075, 1, 0]
# pulled from "tactics_work/kalah-results-1-5-1-1-2.json" :
TDATA[(1, 5, 1, 1, 2)] = \
    [28, 1076, 82, 0, 1, 2245, 141, 1183, 125, 2, 0, 3151, 1, 1649, 992, 165, 5, 659]
# pulled from "tactics_work/kalah-results-1-5-1-1-3.json" :
TDATA[(1, 5, 1, 1, 3)] = \
    [510, 0, 3, 1024, 1876, 288, 1, 1, 839, 2, 2, 1544, 44, 2, 120, 1235, 199, 2568]
# pulled from "tactics_work/kalah-results-1-5-1-2-0.json" :
TDATA[(1, 5, 1, 2, 0)] = \
    [1369, 3108, 790, 594, 0, 3, 1907, 0, 2, 196, 1, 2774, 662, 98, 1480, 1001, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-1-2-1.json" :
TDATA[(1, 5, 1, 2, 1)] = \
    [0, 521, 2690, 966, 1, 2, 2, 967, 2793, 100, 2688, 3, 1, 0, 0, 640, 2, 615]
# pulled from "tactics_work/kalah-results-1-5-1-2-2.json" :
TDATA[(1, 5, 1, 2, 2)] = \
    [498, 731, 786, 0, 0, 1651, 3946, 0, 1530, 840, 2, 2, 482, 443, 670, 1570, 2, 2]
# pulled from "tactics_work/kalah-results-1-5-1-2-3.json" :
TDATA[(1, 5, 1, 2, 3)] = \
    [1272, 0, 949, 0, 0, 0, 551, 0, 0, 1, 0, 1340, 0, 2, 598, 0, 106, 0]
# pulled from "tactics_work/kalah-results-1-5-2-0-0.json" :
TDATA[(1, 5, 2, 0, 0)] = \
    [1, 1, 1, 1, 1, 950, 1, 1, 1, 1, 1, 2, 401, 0, 1, 0, 7, 1]
# pulled from "tactics_work/kalah-results-1-5-2-0-1.json" :
TDATA[(1, 5, 2, 0, 1)] = \
    [0, 1, 787, 295, 1, 1, 1, 1, 0, 1, 1, 1, 0, 584, 1246, 0, 0, 2]
# pulled from "tactics_work/kalah-results-1-5-2-0-2.json" :
TDATA[(1, 5, 2, 0, 2)] = \
    [0, 2, 1, 492, 1, 3, 1, 664, 1, 1, 36, 0, 1, 1, 2, 84, 683, 1]
# pulled from "tactics_work/kalah-results-1-5-2-0-3.json" :
TDATA[(1, 5, 2, 0, 3)] = \
    [0, 0, 2, 620, 1717, 1415, 0, 776, 0, 875, 0, 155, 2, 1, 624, 2, 1, 1]
# pulled from "tactics_work/kalah-results-1-5-2-1-0.json" :
TDATA[(1, 5, 2, 1, 0)] = \
    [1, 2, 2, 1, 1, 0, 0, 1, 368, 1, 1, 1, 0, 1, 2, 1, 59, 0]
# pulled from "tactics_work/kalah-results-1-5-2-1-1.json" :
TDATA[(1, 5, 2, 1, 1)] = \
    [1, 573, 2, 124, 0, 1251, 1, 1, 2, 858, 0, 1, 1, 2, 472, 1, 1, 2]
# pulled from "tactics_work/kalah-results-1-5-2-1-2.json" :
TDATA[(1, 5, 2, 1, 2)] = \
    [1, 334, 2, 1, 1, 40, 1, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 1]
# pulled from "tactics_work/kalah-results-1-5-2-1-3.json" :
TDATA[(1, 5, 2, 1, 3)] = \
    [848, 1, 0, 1, 1, 0, 0, 2, 269, 1, 0, 1, 0, 1, 721, 107, 3, 0]
# pulled from "tactics_work/kalah-results-1-5-2-2-0.json" :
TDATA[(1, 5, 2, 2, 0)] = \
    [239, 0, 1328, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 220, 1]
# pulled from "tactics_work/kalah-results-1-5-2-2-1.json" :
TDATA[(1, 5, 2, 2, 1)] = \
    [0, 1, 0, 0, 1562, 3, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-5-2-2-2.json" :
TDATA[(1, 5, 2, 2, 2)] = \
    [1, 2, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1029, 0, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-5-2-2-3.json" :
TDATA[(1, 5, 2, 2, 3)] = \
    [1, 1, 565, 0, 1767, 1586, 0, 0, 1, 3, 0, 2, 1, 1, 2, 0, 1, 1]
# pulled from "tactics_work/kalah-results-1-5-3-0-0.json" :
TDATA[(1, 5, 3, 0, 0)] = \
    [3987, 6244, 0, 1127, 322, 1616, 1, 7, 5, 9, 0, 4, 1736, 1261, 3590, 60, 603, 5]
# pulled from "tactics_work/kalah-results-1-5-3-0-1.json" :
TDATA[(1, 5, 3, 0, 1)] = \
    [2044, 439, 12530, 831, 2869, 2309, 3, 1, 6, 3, 2, 5, 0, 2638, 0, 389, 370, 1836]
# pulled from "tactics_work/kalah-results-1-5-3-0-2.json" :
TDATA[(1, 5, 3, 0, 2)] = \
    [1429, 3602, 1963, 2004, 0, 1949, 4, 5, 5, 6, 4, 2, 5809, 2045, 3116, 2657, 1616, 864]
# pulled from "tactics_work/kalah-results-1-5-3-0-3.json" :
TDATA[(1, 5, 3, 0, 3)] = \
    [2136, 1415, 263, 5386, 4639, 1, 1, 0, 12, 2, 2, 4, 5782, 970, 1590, 1, 1, 1353]
# pulled from "tactics_work/kalah-results-1-5-3-1-0.json" :
TDATA[(1, 5, 3, 1, 0)] = \
    [0, 4589, 2810, 3012, 846, 4431, 0, 0, 1, 1, 3, 4, 2328, 0, 1995, 0, 0, 7540]
# pulled from "tactics_work/kalah-results-1-5-3-1-1.json" :
TDATA[(1, 5, 3, 1, 1)] = \
    [1769, 5411, 1692, 4336, 0, 2648, 4, 9, 5, 5, 4, 1, 1, 566, 351, 3150, 1898, 2427]
# pulled from "tactics_work/kalah-results-1-5-3-1-2.json" :
TDATA[(1, 5, 3, 1, 2)] = \
    [2041, 457, 4626, 2644, 5674, 1686, 0, 0, 2, 0, 0, 1, 5860, 2868, 2332, 1336, 0, 2886]
# pulled from "tactics_work/kalah-results-1-5-3-1-3.json" :
TDATA[(1, 5, 3, 1, 3)] = \
    [1809, 1, 0, 2592, 2122, 3985, 0, 9, 0, 1, 2, 8, 3415, 6126, 1465, 2377, 2, 1447]
# pulled from "tactics_work/kalah-results-1-5-3-2-0.json" :
TDATA[(1, 5, 3, 2, 0)] = \
    [7, 1217, 881, 2230, 2987, 1394, 7, 5, 5, 1, 2, 0, 6748, 4073, 1926, 0, 0, 3175]
# pulled from "tactics_work/kalah-results-1-5-3-2-1.json" :
TDATA[(1, 5, 3, 2, 1)] = \
    [903, 1, 0, 2, 7138, 759, 5, 0, 4, 4, 0, 0, 845, 4653, 6957, 47, 2129, 209]
# pulled from "tactics_work/kalah-results-1-5-3-2-2.json" :
TDATA[(1, 5, 3, 2, 2)] = \
    [2655, 8558, 967, 3245, 125, 4, 4, 3, 7, 7, 4, 1, 1755, 0, 661, 2193, 5236, 4171]
# pulled from "tactics_work/kalah-results-1-5-3-2-3.json" :
TDATA[(1, 5, 3, 2, 3)] = \
    [263, 2, 3266, 4237, 2333, 421, 4, 0, 3, 0, 5, 6, 3658, 4771, 1025, 0, 430, 0]
# pulled from "tactics_work/kalah-results-1-5-4-0-0.json" :
TDATA[(1, 5, 4, 0, 0)] = \
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1942, 1, 1, 0]
# pulled from "tactics_work/kalah-results-1-5-4-0-1.json" :
TDATA[(1, 5, 4, 0, 1)] = \
    [1188, 125, 858, 1216, 3219, 0, 3, 1, 3, 0, 1, 0, 1, 1, 1, 1666, 1, 1]
# pulled from "tactics_work/kalah-results-1-5-4-0-2.json" :
TDATA[(1, 5, 4, 0, 2)] = \
    [1736, 2, 0, 0, 2135, 358, 4, 4, 2, 2, 4, 4, 0, 111, 156, 3, 0, 1115]
# pulled from "tactics_work/kalah-results-1-5-4-0-3.json" :
TDATA[(1, 5, 4, 0, 3)] = \
    [0, 1540, 1159, 1, 2, 1, 3, 1, 1, 1, 0, 0, 2, 1137, 2, 1342, 1088, 2]
# pulled from "tactics_work/kalah-results-1-5-4-1-0.json" :
TDATA[(1, 5, 4, 1, 0)] = \
    [1, 1208, 0, 0, 0, 1328, 3, 0, 0, 3, 3, 2, 1575, 0, 2, 0, 0, 1]
# pulled from "tactics_work/kalah-results-1-5-4-1-1.json" :
TDATA[(1, 5, 4, 1, 1)] = \
    [1, 1, 1486, 1, 1, 1, 4, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1520]
# pulled from "tactics_work/kalah-results-1-5-4-1-2.json" :
TDATA[(1, 5, 4, 1, 2)] = \
    [1, 1458, 2540, 1, 291, 2, 1, 0, 6, 0, 0, 6, 0, 0, 1, 2259, 838, 0]
# pulled from "tactics_work/kalah-results-1-5-4-1-3.json" :
TDATA[(1, 5, 4, 1, 3)] = \
    [1760, 1, 1050, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 109, 876]
# pulled from "tactics_work/kalah-results-1-5-4-2-0.json" :
TDATA[(1, 5, 4, 2, 0)] = \
    [1, 84, 0, 365, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1041, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 5, 4, 2, 1)] = \
    [1, 84, 0, 365, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1041, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 5, 4, 2, 2)] = \
    [1, 84, 0, 365, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1041, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 5, 4, 2, 3)] = \
    [1, 84, 0, 365, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1041, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-1-0-0.json" :
TDATA[(1, 6, 1, 0, 0)] = \
    [87, 326, 1863, 0, 1, 0, 2324, 932, 523, 339, 865, 2, 995, 626, 115, 1595, 395, 1059]
# pulled from "tactics_work/kalah-results-1-6-1-0-1.json" :
TDATA[(1, 6, 1, 0, 1)] = \
    [0, 2908, 515, 529, 2, 1405, 2333, 1284, 35, 0, 875, 2, 1, 1, 357, 931, 0, 2]
# pulled from "tactics_work/kalah-results-1-6-1-0-2.json" :
TDATA[(1, 6, 1, 0, 2)] = \
    [1, 1, 0, 0, 746, 1, 88, 0, 979, 0, 375, 1, 1, 1, 2, 0, 1373, 2]
# pulled from "tactics_work/kalah-results-1-6-1-0-3.json" :
TDATA[(1, 6, 1, 0, 3)] = \
    [900, 1281, 660, 0, 941, 3020, 2581, 0, 3004, 872, 2, 2067, 0, 15, 0, 525, 417, 269]
# pulled from "tactics_work/kalah-results-1-6-1-1-0.json" :
TDATA[(1, 6, 1, 1, 0)] = \
    [2, 1080, 487, 2306, 0, 189, 2953, 1946, 505, 145, 0, 1129, 390, 2, 0, 445, 775, 0]
# pulled from "tactics_work/kalah-results-1-6-1-1-1.json" :
TDATA[(1, 6, 1, 1, 1)] = \
    [192, 407, 673, 1056, 1, 1808, 2159, 602, 0, 0, 2, 0, 0, 503, 74, 369, 667, 3125]
# pulled from "tactics_work/kalah-results-1-6-1-1-2.json" :
TDATA[(1, 6, 1, 1, 2)] = \
    [947, 0, 911, 367, 494, 1300, 2099, 394, 1, 0, 773, 153, 1, 614, 378, 0, 625, 1689]
# pulled from "tactics_work/kalah-results-1-6-1-1-3.json" :
TDATA[(1, 6, 1, 1, 3)] = \
    [32, 1335, 0, 1577, 0, 258, 4165, 0, 0, 0, 0, 741, 54, 2296, 0, 2, 815, 1]
# pulled from "tactics_work/kalah-results-1-6-1-2-0.json" :
TDATA[(1, 6, 1, 2, 0)] = \
    [1212, 0, 987, 434, 1647, 22, 915, 3, 0, 0, 0, 2298, 186, 2, 395, 1, 923, 531]
# pulled from "tactics_work/kalah-results-1-6-1-2-1.json" :
TDATA[(1, 6, 1, 2, 1)] = \
    [1910, 1057, 847, 0, 0, 1895, 627, 0, 1815, 552, 2, 0, 132, 0, 5, 0, 631, 0]
# pulled from "tactics_work/kalah-results-1-6-1-2-2.json" :
TDATA[(1, 6, 1, 2, 2)] = \
    [2, 1382, 2137, 0, 0, 1083, 1106, 594, 357, 609, 377, 0, 0, 239, 2, 204, 484, 3]
# pulled from "tactics_work/kalah-results-1-6-1-2-3.json" :
TDATA[(1, 6, 1, 2, 3)] = \
    [591, 1, 2, 104, 958, 1628, 2354, 60, 1, 2, 1, 1087, 1075, 0, 1490, 1, 598, 129]
# pulled from "tactics_work/kalah-results-1-6-2-0-0.json" :
TDATA[(1, 6, 2, 0, 0)] = \
    [797, 1, 1, 1, 1, 0, 47, 1, 423, 1, 0, 1, 2, 574, 0, 2, 654, 1]
# pulled from "tactics_work/kalah-results-1-6-2-0-1.json" :
TDATA[(1, 6, 2, 0, 1)] = \
    [2, 0, 818, 1, 1, 0, 939, 1, 3, 62, 1, 0, 1, 1, 54, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-2-0-2.json" :
TDATA[(1, 6, 2, 0, 2)] = \
    [265, 2, 2, 1, 0, 1, 1, 333, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2]
# pulled from "tactics_work/kalah-results-1-6-2-0-3.json" :
TDATA[(1, 6, 2, 0, 3)] = \
    [0, 1, 1, 0, 1, 0, 765, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1263]
# pulled from "tactics_work/kalah-results-1-6-2-1-0.json" :
TDATA[(1, 6, 2, 1, 0)] = \
    [1, 0, 1, 1, 1, 606, 1, 2, 1, 1, 0, 1, 2, 0, 0, 1, 1, 774]
# pulled from "tactics_work/kalah-results-1-6-2-1-1.json" :
TDATA[(1, 6, 2, 1, 1)] = \
    [1, 2, 1207, 0, 2, 1089, 5, 1, 1, 0, 2, 1, 2, 1, 0, 1, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-2-1-2.json" :
TDATA[(1, 6, 2, 1, 2)] = \
    [1, 1, 1626, 1, 1888, 1112, 7, 0, 2, 1, 2, 1, 1, 0, 0, 657, 1, 814]
# pulled from "tactics_work/kalah-results-1-6-2-1-3.json" :
TDATA[(1, 6, 2, 1, 3)] = \
    [257, 1, 1, 1720, 1139, 1, 1, 1, 3, 1, 2, 1, 2, 851, 1, 2, 0, 1]
# pulled from "tactics_work/kalah-results-1-6-2-2-0.json" :
TDATA[(1, 6, 2, 2, 0)] = \
    [1, 648, 0, 2290, 3171, 364, 0, 1, 1, 2, 2, 2, 3, 1, 1, 2, 678, 2]
# pulled from "tactics_work/kalah-results-1-6-2-2-1.json" :
TDATA[(1, 6, 2, 2, 1)] = \
    [0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1261, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-2-2-2.json" :
TDATA[(1, 6, 2, 2, 2)] = \
    [198, 3, 2257, 1, 937, 1, 2, 1, 0, 4, 1, 1, 0, 1, 1, 1, 365, 1]
# pulled from "tactics_work/kalah-results-1-6-2-2-3.json" :
TDATA[(1, 6, 2, 2, 3)] = \
    [2, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 2, 2, 1, 0, 1702, 1591]
# pulled from "tactics_work/kalah-results-1-6-3-0-0.json" :
TDATA[(1, 6, 3, 0, 0)] = \
    [0, 1792, 510, 0, 4813, 0, 5, 7, 10, 5, 1, 0, 3123, 2605, 1842, 2508, 0, 1956]
# pulled from "tactics_work/kalah-results-1-6-3-0-1.json" :
TDATA[(1, 6, 3, 0, 1)] = \
    [2992, 2, 2510, 8834, 519, 2, 7, 8, 3, 1, 5, 2, 1178, 5895, 0, 2087, 942, 1974]
# pulled from "tactics_work/kalah-results-1-6-3-0-2.json" :
TDATA[(1, 6, 3, 0, 2)] = \
    [3051, 5888, 529, 0, 1746, 1749, 7, 3, 4, 2, 0, 4, 2903, 1652, 0, 995, 383, 2728]
# pulled from "tactics_work/kalah-results-1-6-3-0-3.json" :
TDATA[(1, 6, 3, 0, 3)] = \
    [1787, 1866, 4665, 1112, 3, 3093, 1, 0, 4, 9, 1, 10, 0, 1178, 0, 1645, 178, 3560]
# pulled from "tactics_work/kalah-results-1-6-3-1-0.json" :
TDATA[(1, 6, 3, 1, 0)] = \
    [854, 1, 2440, 5360, 1917, 2168, 4, 5, 1, 1, 0, 10, 1305, 1279, 0, 2891, 2453, 4328]
# pulled from "tactics_work/kalah-results-1-6-3-1-1.json" :
TDATA[(1, 6, 3, 1, 1)] = \
    [4120, 0, 5352, 8176, 1102, 1755, 1, 5, 2, 4, 2, 3, 1410, 4486, 2999, 844, 3908, 2]
# pulled from "tactics_work/kalah-results-1-6-3-1-2.json" :
TDATA[(1, 6, 3, 1, 2)] = \
    [1302, 2587, 3271, 3947, 104, 1425, 14, 11, 2, 3, 2, 3, 3600, 1355, 1, 2, 1266, 1779]
# pulled from "tactics_work/kalah-results-1-6-3-1-3.json" :
TDATA[(1, 6, 3, 1, 3)] = \
    [1227, 0, 4164, 1617, 0, 1608, 1, 0, 5, 5, 0, 7, 4726, 1668, 10776, 327, 2016, 112]
# pulled from "tactics_work/kalah-results-1-6-3-2-0.json" :
TDATA[(1, 6, 3, 2, 0)] = \
    [2, 4573, 2, 3830, 4894, 1978, 8, 4, 4, 3, 1, 4, 4422, 2, 663, 5112, 779, 1719]
# pulled from "tactics_work/kalah-results-1-6-3-2-1.json" :
TDATA[(1, 6, 3, 2, 1)] = \
    [1277, 159, 5858, 4475, 62, 2, 7, 8, 1, 1, 11, 0, 1462, 1, 5068, 2460, 2487, 0]
# pulled from "tactics_work/kalah-results-1-6-3-2-2.json" :
TDATA[(1, 6, 3, 2, 2)] = \
    [1, 0, 7065, 3, 2967, 2639, 2, 1, 1, 2, 3, 8, 0, 945, 0, 5, 1269, 2998]
# pulled from "tactics_work/kalah-results-1-6-3-2-3.json" :
TDATA[(1, 6, 3, 2, 3)] = \
    [2763, 1904, 1, 3055, 2570, 298, 2, 6, 1, 1, 0, 0, 2021, 501, 6850, 1168, 3952, 3263]
# pulled from "tactics_work/kalah-results-1-6-4-0-0.json" :
TDATA[(1, 6, 4, 0, 0)] = \
    [1, 0, 1, 3, 1, 1, 1, 1, 2, 1, 0, 1, 1575, 1, 0, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-4-0-1.json" :
TDATA[(1, 6, 4, 0, 1)] = \
    [1, 1, 1360, 0, 1, 1560, 1, 1, 4, 1, 1, 1, 1, 1, 276, 1, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-4-0-2.json" :
TDATA[(1, 6, 4, 0, 2)] = \
    [1, 2, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1696, 1, 1, 2, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-4-0-3.json" :
TDATA[(1, 6, 4, 0, 3)] = \
    [1, 1, 1, 1, 0, 235, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-4-1-0.json" :
TDATA[(1, 6, 4, 1, 0)] = \
    [0, 0, 1, 1827, 1, 1071, 1, 1, 2, 1, 2, 0, 3, 1, 0, 1, 802, 1]
# pulled from "tactics_work/kalah-results-1-6-4-1-1.json" :
TDATA[(1, 6, 4, 1, 1)] = \
    [1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1838, 1, 436, 0, 1, 1]
# pulled from "tactics_work/kalah-results-1-6-4-1-2.json" :
TDATA[(1, 6, 4, 1, 2)] = \
    [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 6, 4, 1, 3)] = \
    [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 6, 4, 2, 0)] = \
    [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 6, 4, 2, 1)] = \
    [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 6, 4, 2, 2)] = \
    [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1]
# file missing; repeating content :
TDATA[(1, 6, 4, 2, 3)] = \
    [1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-1-0-0.json" :
TDATA[(2, 4, 1, 0, 0)] = \
    [2, 1914, 2210, 0, 2760, 931, 3, 0, 4, 1, 1, 1, 2, 1938, 2348, 1992, 0, 4065]
# pulled from "tactics_work/kalah-results-2-4-1-0-1.json" :
TDATA[(2, 4, 1, 0, 1)] = \
    [2, 2679, 3039, 2, 1, 2, 0, 8, 0, 0, 5, 6, 0, 628, 828, 0, 1170, 1624]
# pulled from "tactics_work/kalah-results-2-4-1-0-2.json" :
TDATA[(2, 4, 1, 0, 2)] = \
    [4955, 1513, 1321, 1991, 2, 832, 1, 7, 3, 6, 3, 3, 1, 2121, 1000, 1964, 1283, 1446]
# pulled from "tactics_work/kalah-results-2-4-1-0-3.json" :
TDATA[(2, 4, 1, 0, 3)] = \
    [4918, 1028, 405, 3, 3186, 0, 7, 7, 1, 0, 2, 1, 1205, 1995, 305, 838, 6861, 2]
# pulled from "tactics_work/kalah-results-2-4-1-1-0.json" :
TDATA[(2, 4, 1, 1, 0)] = \
    [3364, 861, 2195, 2, 0, 1836, 3, 7, 3, 7, 7, 0, 1017, 1943, 1533, 0, 1985, 2]
# pulled from "tactics_work/kalah-results-2-4-1-1-1.json" :
TDATA[(2, 4, 1, 1, 1)] = \
    [1647, 4452, 1604, 3352, 0, 1, 6, 2, 3, 1, 7, 7, 1, 3615, 0, 0, 3, 2]
# pulled from "tactics_work/kalah-results-2-4-1-1-2.json" :
TDATA[(2, 4, 1, 1, 2)] = \
    [28, 1991, 513, 3969, 1746, 2, 0, 2, 1, 2, 6, 1, 2431, 2, 2751, 434, 1460, 0]
# pulled from "tactics_work/kalah-results-2-4-1-1-3.json" :
TDATA[(2, 4, 1, 1, 3)] = \
    [5685, 841, 2714, 1786, 1364, 654, 0, 8, 0, 0, 0, 0, 1552, 2, 1076, 166, 3895, 3424]
# pulled from "tactics_work/kalah-results-2-4-1-2-0.json" :
TDATA[(2, 4, 1, 2, 0)] = \
    [5823, 4508, 2, 3972, 1801, 388, 1, 3, 1, 0, 4, 5, 1235, 2332, 792, 591, 4216, 1552]
# pulled from "tactics_work/kalah-results-2-4-1-2-1.json" :
TDATA[(2, 4, 1, 2, 1)] = \
    [4263, 1777, 1363, 2550, 586, 727, 2, 9, 3, 0, 6, 8, 1, 3, 5076, 0, 3079, 805]
# pulled from "tactics_work/kalah-results-2-4-1-2-2.json" :
TDATA[(2, 4, 1, 2, 2)] = \
    [3930, 506, 3, 0, 324, 5917, 1, 6, 1, 5, 11, 12, 939, 1307, 1940, 2, 1052, 2]
# pulled from "tactics_work/kalah-results-2-4-1-2-3.json" :
TDATA[(2, 4, 1, 2, 3)] = \
    [1550, 1705, 686, 0, 209, 5882, 5, 1, 2, 7, 8, 8, 3240, 3062, 2790, 1, 1335, 911]
# pulled from "tactics_work/kalah-results-2-4-2-0-0.json" :
TDATA[(2, 4, 2, 0, 0)] = \
    [1, 0, 1056, 2, 1054, 155, 1, 1, 0, 1, 3, 0, 1608, 1160, 1, 1, 0, 2269]
# pulled from "tactics_work/kalah-results-2-4-2-0-1.json" :
TDATA[(2, 4, 2, 0, 1)] = \
    [1, 1, 1217, 1, 1288, 755, 1, 2, 1, 1, 1, 1, 0, 1, 862, 1, 1, 2]
# pulled from "tactics_work/kalah-results-2-4-2-0-2.json" :
TDATA[(2, 4, 2, 0, 2)] = \
    [1, 1, 1, 0, 1, 0, 1, 1, 3, 2, 0, 1, 1101, 0, 1, 1, 908, 1898]
# pulled from "tactics_work/kalah-results-2-4-2-0-3.json" :
TDATA[(2, 4, 2, 0, 3)] = \
    [2, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1517, 1, 1, 1, 0, 478]
# pulled from "tactics_work/kalah-results-2-4-2-1-0.json" :
TDATA[(2, 4, 2, 1, 0)] = \
    [1, 1539, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 0, 2]
# pulled from "tactics_work/kalah-results-2-4-2-1-1.json" :
TDATA[(2, 4, 2, 1, 1)] = \
    [1792, 761, 1367, 0, 1, 2, 0, 3, 1, 0, 5, 1, 2, 1, 0, 1, 1694, 1]
# pulled from "tactics_work/kalah-results-2-4-2-1-2.json" :
TDATA[(2, 4, 2, 1, 2)] = \
    [2297, 1061, 1, 1, 0, 1, 1, 0, 3, 0, 1, 0, 0, 1301, 0, 1, 1, 2]
# pulled from "tactics_work/kalah-results-2-4-2-1-3.json" :
TDATA[(2, 4, 2, 1, 3)] = \
    [2, 1, 914, 0, 1, 506, 1, 3, 3, 1, 0, 1, 1, 1, 1, 1, 1, 41]
# pulled from "tactics_work/kalah-results-2-4-2-2-0.json" :
TDATA[(2, 4, 2, 2, 0)] = \
    [0, 1728, 0, 1, 1, 2, 3, 0, 4, 3, 2, 2, 1392, 349, 0, 2, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-2-2-1.json" :
TDATA[(2, 4, 2, 2, 1)] = \
    [1, 1, 1, 3, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1283, 0]
# pulled from "tactics_work/kalah-results-2-4-2-2-2.json" :
TDATA[(2, 4, 2, 2, 2)] = \
    [1, 1, 1, 2, 1, 12, 0, 1, 1, 1, 1, 0, 1782, 1, 3, 1108, 0, 1]
# pulled from "tactics_work/kalah-results-2-4-2-2-3.json" :
TDATA[(2, 4, 2, 2, 3)] = \
    [1, 1, 0, 79, 969, 2, 1, 0, 1, 2, 0, 1, 1982, 0, 1468, 0, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-3-0-0.json" :
TDATA[(2, 4, 3, 0, 0)] = \
    [78, 5226, 4296, 5451, 1687, 4350, 7, 1, 8, 2, 0, 0, 6559, 2, 3513, 845, 7165, 5]
# pulled from "tactics_work/kalah-results-2-4-3-0-1.json" :
TDATA[(2, 4, 3, 0, 1)] = \
    [1986, 1853, 7863, 1, 414, 1754, 6, 2, 1, 3, 1, 0, 1177, 1978, 1459, 385, 3542, 2]
# pulled from "tactics_work/kalah-results-2-4-3-0-2.json" :
TDATA[(2, 4, 3, 0, 2)] = \
    [2956, 3422, 170, 5194, 7163, 63, 6, 4, 2, 1, 5, 2, 2454, 3237, 0, 2488, 2503, 1879]
# pulled from "tactics_work/kalah-results-2-4-3-0-3.json" :
TDATA[(2, 4, 3, 0, 3)] = \
    [0, 3659, 3500, 1, 1544, 1174, 11, 6, 2, 2, 4, 3, 3496, 3478, 0, 2267, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-3-1-0.json" :
TDATA[(2, 4, 3, 1, 0)] = \
    [0, 395, 4291, 673, 3309, 26, 1, 0, 1, 0, 1, 0, 4561, 542, 1534, 3202, 1903, 2693]
# pulled from "tactics_work/kalah-results-2-4-3-1-1.json" :
TDATA[(2, 4, 3, 1, 1)] = \
    [3359, 6823, 914, 1496, 13, 0, 1, 5, 2, 2, 6, 1, 1151, 1705, 748, 0, 0, 2841]
# pulled from "tactics_work/kalah-results-2-4-3-1-2.json" :
TDATA[(2, 4, 3, 1, 2)] = \
    [1, 5178, 1020, 1437, 895, 1658, 7, 5, 3, 2, 0, 1, 409, 0, 252, 2, 1464, 1]
# pulled from "tactics_work/kalah-results-2-4-3-1-3.json" :
TDATA[(2, 4, 3, 1, 3)] = \
    [2270, 2022, 3255, 3333, 0, 2668, 5, 0, 5, 1, 3, 1, 9961, 1601, 0, 1578, 3331, 2318]
# pulled from "tactics_work/kalah-results-2-4-3-2-0.json" :
TDATA[(2, 4, 3, 2, 0)] = \
    [1, 0, 5416, 3668, 3484, 3253, 2, 3, 4, 1, 5, 6, 2916, 1993, 1752, 567, 4500, 916]
# pulled from "tactics_work/kalah-results-2-4-3-2-1.json" :
TDATA[(2, 4, 3, 2, 1)] = \
    [2, 610, 218, 206, 7728, 6496, 2, 5, 10, 0, 0, 3, 340, 3713, 758, 2818, 353, 365]
# pulled from "tactics_work/kalah-results-2-4-3-2-2.json" :
TDATA[(2, 4, 3, 2, 2)] = \
    [1568, 613, 0, 945, 2, 6193, 2, 0, 6, 2, 7, 9, 2042, 1267, 4802, 3732, 1276, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-3.json" :
TDATA[(2, 4, 3, 2, 3)] = \
    [2335, 1321, 0, 4939, 1390, 983, 2, 2, 3, 0, 9, 11, 3436, 1722, 5712, 177, 1, 3848]
# pulled from "tactics_work/kalah-results-2-4-4-0-0.json" :
TDATA[(2, 4, 4, 0, 0)] = \
    [1580, 2, 1335, 1, 1, 1, 5, 1, 2, 5, 1, 1, 559, 1, 1, 829, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-4-0-1.json" :
TDATA[(2, 4, 4, 0, 1)] = \
    [1602, 1779, 1033, 1, 1, 1, 1, 0, 1, 0, 4, 1, 1, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-4-0-2.json" :
TDATA[(2, 4, 4, 0, 2)] = \
    [1952, 1083, 1, 1, 1, 3, 1, 6, 1, 3, 2, 1, 0, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-4-0-3.json" :
TDATA[(2, 4, 4, 0, 3)] = \
    [3, 1, 0, 1205, 1545, 1369, 2, 0, 2, 0, 1, 0, 1197, 3, 0, 1144, 793, 0]
# pulled from "tactics_work/kalah-results-2-4-4-1-0.json" :
TDATA[(2, 4, 4, 1, 0)] = \
    [0, 1257, 3, 1, 1, 3276, 1, 4, 1, 0, 4, 0, 0, 1, 0, 0, 1, 117]
# pulled from "tactics_work/kalah-results-2-4-4-1-1.json" :
TDATA[(2, 4, 4, 1, 1)] = \
    [1, 2, 870, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1503, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-4-1-2.json" :
TDATA[(2, 4, 4, 1, 2)] = \
    [2, 1880, 1, 0, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 795, 0, 0, 1]
# pulled from "tactics_work/kalah-results-2-4-4-1-3.json" :
TDATA[(2, 4, 4, 1, 3)] = \
    [236, 1, 2, 1, 1, 1, 4, 1, 1, 0, 2, 1, 2561, 1, 1, 2, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-4-2-0.json" :
TDATA[(2, 4, 4, 2, 0)] = \
    [105, 1669, 2433, 1, 0, 218, 2, 2, 0, 0, 5, 2, 0, 1, 1423, 2, 1358, 0]
# pulled from "tactics_work/kalah-results-2-4-4-2-1.json" :
TDATA[(2, 4, 4, 2, 1)] = \
    [1194, 2, 1, 1886, 2, 2293, 0, 2, 0, 1, 0, 2, 1, 1, 1651, 0, 0, 1]
# pulled from "tactics_work/kalah-results-2-4-4-2-2.json" :
TDATA[(2, 4, 4, 2, 2)] = \
    [1, 1, 1, 453, 1, 1188, 1, 2, 1, 2, 0, 1, 1, 1, 1838, 1, 256, 3]
# pulled from "tactics_work/kalah-results-2-4-4-2-3.json" :
TDATA[(2, 4, 4, 2, 3)] = \
    [2, 2, 0, 449, 1376, 1062, 2, 0, 1, 1, 2, 3, 1, 0, 2, 2, 1, 0]
# pulled from "tactics_work/kalah-results-2-3-1-0-0.json" :
TDATA[(2, 3, 1, 0, 0)] = \
    [0, 0, 967, 470, 1998, 2377, 2, 2, 2, 7, 2, 0, 0, 232, 1, 1, 4194, 0]
# pulled from "tactics_work/kalah-results-2-3-1-0-1.json" :
TDATA[(2, 3, 1, 0, 1)] = \
    [1, 1, 1914, 1, 0, 3469, 5, 0, 2, 1, 5, 5, 2, 0, 1, 1, 0, 2]
# pulled from "tactics_work/kalah-results-2-3-1-0-2.json" :
TDATA[(2, 3, 1, 0, 2)] = \
    [2, 3624, 4648, 1257, 2161, 2502, 3, 6, 0, 3, 1, 5, 1485, 0, 2, 897, 1610, 0]
# pulled from "tactics_work/kalah-results-2-3-1-0-3.json" :
TDATA[(2, 3, 1, 0, 3)] = \
    [0, 0, 2386, 0, 1, 3741, 5, 0, 1, 1, 2, 2, 0, 1, 1, 1, 0, 1]
# pulled from "tactics_work/kalah-results-2-3-1-1-0.json" :
TDATA[(2, 3, 1, 1, 0)] = \
    [1215, 516, 1491, 1, 0, 1, 1, 4, 2, 1, 2, 6, 1, 1, 1, 1511, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-1-1-1.json" :
TDATA[(2, 3, 1, 1, 1)] = \
    [859, 1, 837, 0, 0, 889, 0, 0, 1, 1, 2, 3, 0, 657, 1, 0, 3, 678]
# pulled from "tactics_work/kalah-results-2-3-1-1-2.json" :
TDATA[(2, 3, 1, 1, 2)] = \
    [2165, 391, 0, 4163, 2058, 429, 3, 1, 1, 12, 1, 0, 1259, 1492, 1, 1, 1506, 0]
# pulled from "tactics_work/kalah-results-2-3-1-1-3.json" :
TDATA[(2, 3, 1, 1, 3)] = \
    [1, 0, 1936, 1395, 0, 1989, 4, 0, 0, 1, 1, 0, 1902, 820, 0, 3107, 368, 2]
# pulled from "tactics_work/kalah-results-2-3-1-2-0.json" :
TDATA[(2, 3, 1, 2, 0)] = \
    [1689, 1141, 1, 0, 771, 3883, 0, 1, 2, 0, 2, 8, 3258, 0, 3133, 2330, 2, 0]
# pulled from "tactics_work/kalah-results-2-3-1-2-1.json" :
TDATA[(2, 3, 1, 2, 1)] = \
    [3803, 3253, 2, 3311, 0, 1803, 0, 9, 2, 4, 2, 5, 2543, 1429, 2257, 0, 4262, 0]
# pulled from "tactics_work/kalah-results-2-3-1-2-2.json" :
TDATA[(2, 3, 1, 2, 2)] = \
    [0, 1014, 141, 0, 1, 1082, 0, 3, 6, 0, 1, 0, 2020, 0, 1, 464, 0, 3]
# pulled from "tactics_work/kalah-results-2-3-1-2-3.json" :
TDATA[(2, 3, 1, 2, 3)] = \
    [0, 1, 488, 1748, 1, 0, 2, 1, 1, 4, 2, 6, 2758, 1116, 0, 2, 0, 1]
# pulled from "tactics_work/kalah-results-2-3-2-0-0.json" :
TDATA[(2, 3, 2, 0, 0)] = \
    [1, 1480, 525, 1, 2, 1195, 2, 1, 1, 1, 6, 2, 1, 1, 1284, 881, 0, 1041]
# pulled from "tactics_work/kalah-results-2-3-2-0-1.json" :
TDATA[(2, 3, 2, 0, 1)] = \
    [1, 1822, 0, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1]
# pulled from "tactics_work/kalah-results-2-3-2-0-2.json" :
TDATA[(2, 3, 2, 0, 2)] = \
    [51, 1, 0, 1, 1979, 1669, 2, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-2-0-3.json" :
TDATA[(2, 3, 2, 0, 3)] = \
    [1, 1110, 1, 1582, 0, 1, 1, 4, 1, 2, 6, 2, 1102, 2, 1, 0, 1, 2]
# pulled from "tactics_work/kalah-results-2-3-2-1-0.json" :
TDATA[(2, 3, 2, 1, 0)] = \
    [1, 1, 1840, 1, 0, 1, 1, 2, 1, 3, 1, 0, 1906, 1, 1, 1, 3407, 1]
# pulled from "tactics_work/kalah-results-2-3-2-1-1.json" :
TDATA[(2, 3, 2, 1, 1)] = \
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-3-2-1-2.json" :
TDATA[(2, 3, 2, 1, 2)] = \
    [1, 2, 0, 1800, 2, 1707, 1, 1, 1, 1, 1, 2, 453, 1, 1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-2-1-3.json" :
TDATA[(2, 3, 2, 1, 3)] = \
    [1, 1988, 0, 1, 0, 0, 1, 0, 2, 5, 1, 0, 1238, 1, 1286, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-3-2-2-0.json" :
TDATA[(2, 3, 2, 2, 0)] = \
    [0, 0, 2, 1567, 1, 2, 1, 3, 1, 2, 2, 0, 0, 1595, 1, 1, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-2-2-1.json" :
TDATA[(2, 3, 2, 2, 1)] = \
    [1, 1, 1, 1, 1085, 754, 1, 0, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-3-2-2-2.json" :
TDATA[(2, 3, 2, 2, 2)] = \
    [2, 1, 461, 923, 5227, 2, 0, 1, 5, 2, 1, 0, 1, 0, 1, 1, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-2-2-3.json" :
TDATA[(2, 3, 2, 2, 3)] = \
    [1670, 0, 2, 1486, 1359, 4149, 0, 2, 0, 6, 0, 2, 1104, 0, 0, 0, 1640, 2]
# pulled from "tactics_work/kalah-results-2-3-3-0-0.json" :
TDATA[(2, 3, 3, 0, 0)] = \
    [1975, 1503, 2257, 4116, 1, 1289, 6, 2, 5, 3, 1, 10, 2495, 4411, 2844, 583, 804, 1660]
# pulled from "tactics_work/kalah-results-2-3-3-0-1.json" :
TDATA[(2, 3, 3, 0, 1)] = \
    [1956, 214, 0, 2796, 0, 1483, 6, 0, 6, 10, 2, 2, 1351, 0, 757, 1740, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-2.json" :
TDATA[(2, 3, 3, 0, 2)] = \
    [2710, 1809, 2, 2729, 3084, 0, 0, 2, 5, 0, 6, 2, 0, 0, 4366, 0, 0, 2497]
# pulled from "tactics_work/kalah-results-2-3-3-0-3.json" :
TDATA[(2, 3, 3, 0, 3)] = \
    [0, 0, 2, 3599, 3181, 3545, 0, 0, 2, 0, 4, 4, 1635, 739, 1218, 1915, 0, 1]
# pulled from "tactics_work/kalah-results-2-3-3-1-0.json" :
TDATA[(2, 3, 3, 1, 0)] = \
    [1601, 2, 0, 1868, 1361, 833, 8, 4, 0, 0, 7, 10, 919, 882, 4636, 1616, 3, 548]
# pulled from "tactics_work/kalah-results-2-3-3-1-1.json" :
TDATA[(2, 3, 3, 1, 1)] = \
    [3169, 1342, 205, 0, 2684, 81, 12, 5, 0, 1, 4, 7, 4974, 0, 1507, 1505, 3709, 1]
# pulled from "tactics_work/kalah-results-2-3-3-1-2.json" :
TDATA[(2, 3, 3, 1, 2)] = \
    [1739, 3924, 1983, 4383, 1633, 0, 1, 11, 6, 0, 5, 5, 5675, 1177, 3, 414, 10, 0]
# pulled from "tactics_work/kalah-results-2-3-3-1-3.json" :
TDATA[(2, 3, 3, 1, 3)] = \
    [2038, 2, 1616, 831, 0, 3366, 2, 0, 1, 1, 1, 1, 2186, 3450, 5513, 829, 1, 1]
# pulled from "tactics_work/kalah-results-2-3-3-2-0.json" :
TDATA[(2, 3, 3, 2, 0)] = \
    [4, 1, 2149, 2483, 746, 4461, 3, 0, 3, 1, 3, 0, 1379, 2636, 3950, 3, 459, 1047]
# pulled from "tactics_work/kalah-results-2-3-3-2-1.json" :
TDATA[(2, 3, 3, 2, 1)] = \
    [1784, 1, 1533, 1294, 1940, 1, 3, 0, 3, 7, 11, 4, 1684, 1658, 3, 3680, 550, 1]
# pulled from "tactics_work/kalah-results-2-3-3-2-2.json" :
TDATA[(2, 3, 3, 2, 2)] = \
    [140, 1844, 3, 3346, 2775, 1197, 4, 2, 0, 3, 6, 2, 0, 1652, 1265, 919, 2333, 2215]
# pulled from "tactics_work/kalah-results-2-3-3-2-3.json" :
TDATA[(2, 3, 3, 2, 3)] = \
    [1492, 3, 433, 1452, 4680, 1178, 8, 4, 0, 1, 13, 3, 1, 1768, 3, 4295, 0, 2296]
# pulled from "tactics_work/kalah-results-2-3-4-0-0.json" :
TDATA[(2, 3, 4, 0, 0)] = \
    [1, 0, 0, 0, 2, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 727, 893]
# pulled from "tactics_work/kalah-results-2-3-4-0-1.json" :
TDATA[(2, 3, 4, 0, 1)] = \
    [2, 1478, 3222, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 2, 1, 0, 0, 867]
# pulled from "tactics_work/kalah-results-2-3-4-0-2.json" :
TDATA[(2, 3, 4, 0, 2)] = \
    [781, 1, 0, 1132, 1177, 1, 1, 0, 1, 1, 1, 2, 1335, 1028, 1, 2395, 2, 1]
# pulled from "tactics_work/kalah-results-2-3-4-0-3.json" :
TDATA[(2, 3, 4, 0, 3)] = \
    [1, 1, 2, 1272, 1665, 1743, 1, 0, 0, 2, 1, 8, 1426, 1011, 0, 1230, 1, 2]
# pulled from "tactics_work/kalah-results-2-3-4-1-0.json" :
TDATA[(2, 3, 4, 1, 0)] = \
    [1, 2085, 54, 3320, 1, 0, 2, 0, 1, 0, 4, 4, 1546, 1, 1, 0, 1, 0]
# pulled from "tactics_work/kalah-results-2-3-4-1-1.json" :
TDATA[(2, 3, 4, 1, 1)] = \
    [0, 1, 1748, 1, 2370, 1096, 1, 2, 5, 5, 4, 6, 1, 1121, 1, 1, 1390, 1]
# pulled from "tactics_work/kalah-results-2-3-4-1-2.json" :
TDATA[(2, 3, 4, 1, 2)] = \
    [1, 1, 1311, 1, 1616, 0, 0, 0, 1, 1, 1, 0, 1, 0, 708, 759, 2, 1]
# pulled from "tactics_work/kalah-results-2-3-4-1-3.json" :
TDATA[(2, 3, 4, 1, 3)] = \
    [0, 112, 0, 0, 1605, 1618, 6, 0, 4, 1, 4, 1, 780, 677, 1390, 0, 2311, 2122]
# pulled from "tactics_work/kalah-results-2-3-4-2-0.json" :
TDATA[(2, 3, 4, 2, 0)] = \
    [223, 0, 0, 0, 2066, 1, 0, 1, 0, 2, 4, 0, 0, 1691, 1618, 0, 2907, 1478]
# pulled from "tactics_work/kalah-results-2-3-4-2-1.json" :
TDATA[(2, 3, 4, 2, 1)] = \
    [1, 1967, 0, 1, 1, 1442, 1, 4, 1, 1, 1, 0, 550, 1, 1041, 1, 1590, 1]
# pulled from "tactics_work/kalah-results-2-3-4-2-2.json" :
TDATA[(2, 3, 4, 2, 2)] = \
    [1, 2828, 1, 1554, 2, 1806, 0, 0, 1, 1, 0, 1, 818, 207, 0, 1979, 1, 1192]
# pulled from "tactics_work/kalah-results-2-3-4-2-3.json" :
TDATA[(2, 3, 4, 2, 3)] = \
    [0, 1951, 1541, 1246, 1, 1468, 0, 1, 0, 0, 2, 6, 103, 1, 1, 1998, 1, 451]
# pulled from "tactics_work/kalah-results-2-5-1-0-0.json" :
TDATA[(2, 5, 1, 0, 0)] = \
    [1577, 2832, 3981, 2, 592, 2, 6, 1, 10, 2, 6, 9, 115, 3548, 651, 0, 0, 1106]
# pulled from "tactics_work/kalah-results-2-5-1-0-1.json" :
TDATA[(2, 5, 1, 0, 1)] = \
    [206, 3434, 2043, 2270, 1, 3718, 0, 5, 7, 5, 0, 1, 1, 2344, 363, 529, 144, 1566]
# pulled from "tactics_work/kalah-results-2-5-1-0-2.json" :
TDATA[(2, 5, 1, 0, 2)] = \
    [2658, 3058, 4081, 638, 2524, 1893, 4, 10, 2, 2, 2, 5, 0, 2203, 1, 2, 0, 1656]
# pulled from "tactics_work/kalah-results-2-5-1-0-3.json" :
TDATA[(2, 5, 1, 0, 3)] = \
    [2642, 1024, 2, 2676, 1252, 2, 3, 2, 2, 3, 0, 2, 4, 955, 1519, 1659, 3, 1033]
# pulled from "tactics_work/kalah-results-2-5-1-1-0.json" :
TDATA[(2, 5, 1, 1, 0)] = \
    [1787, 0, 1237, 1749, 4370, 1, 8, 5, 7, 5, 0, 1, 1025, 0, 1326, 1, 544, 613]
# pulled from "tactics_work/kalah-results-2-5-1-1-1.json" :
TDATA[(2, 5, 1, 1, 1)] = \
    [3599, 3, 2614, 615, 5513, 2, 1, 3, 2, 4, 4, 1, 1, 245, 1, 928, 791, 2703]
# pulled from "tactics_work/kalah-results-2-5-1-1-2.json" :
TDATA[(2, 5, 1, 1, 2)] = \
    [2, 1508, 0, 797, 453, 5655, 0, 4, 5, 1, 2, 4, 623, 1792, 3704, 1085, 1, 2698]
# pulled from "tactics_work/kalah-results-2-5-1-1-3.json" :
TDATA[(2, 5, 1, 1, 3)] = \
    [0, 953, 0, 2658, 1, 3605, 4, 5, 7, 2, 1, 6, 4603, 192, 0, 1, 0, 1335]
# pulled from "tactics_work/kalah-results-2-5-1-2-0.json" :
TDATA[(2, 5, 1, 2, 0)] = \
    [2292, 2, 0, 0, 2, 2, 14, 5, 9, 5, 4, 1, 3, 1573, 972, 3, 454, 2906]
# pulled from "tactics_work/kalah-results-2-5-1-2-1.json" :
TDATA[(2, 5, 1, 2, 1)] = \
    [782, 1976, 805, 0, 1702, 2, 12, 7, 6, 8, 0, 2, 246, 0, 2310, 2911, 1, 1064]
# pulled from "tactics_work/kalah-results-2-5-1-2-2.json" :
TDATA[(2, 5, 1, 2, 2)] = \
    [5116, 764, 0, 2, 2893, 2695, 11, 4, 5, 10, 4, 4, 6747, 3, 0, 2947, 3, 5967]
# pulled from "tactics_work/kalah-results-2-5-1-2-3.json" :
TDATA[(2, 5, 1, 2, 3)] = \
    [856, 711, 1776, 4152, 0, 1, 0, 9, 3, 6, 2, 0, 3, 939, 0, 0, 1, 1107]
# pulled from "tactics_work/kalah-results-2-5-2-0-0.json" :
TDATA[(2, 5, 2, 0, 0)] = \
    [1, 1, 2, 0, 1, 0, 1, 2, 3, 1, 0, 1, 2, 1, 2, 1, 1, 1298]
# pulled from "tactics_work/kalah-results-2-5-2-0-1.json" :
TDATA[(2, 5, 2, 0, 1)] = \
    [0, 1, 1, 1991, 1, 1, 5, 2, 1, 3, 0, 0, 1, 1, 2644, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-5-2-0-2.json" :
TDATA[(2, 5, 2, 0, 2)] = \
    [1, 373, 2, 1, 0, 2, 0, 2, 3, 0, 0, 1, 1, 2, 1, 2, 1686, 1]
# pulled from "tactics_work/kalah-results-2-5-2-0-3.json" :
TDATA[(2, 5, 2, 0, 3)] = \
    [2, 0, 1, 1354, 0, 1305, 2, 6, 3, 0, 0, 0, 1336, 3, 0, 1, 0, 1190]
# pulled from "tactics_work/kalah-results-2-5-2-1-0.json" :
TDATA[(2, 5, 2, 1, 0)] = \
    [1, 1, 1, 0, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-5-2-1-1.json" :
TDATA[(2, 5, 2, 1, 1)] = \
    [445, 1, 1814, 186, 1, 1, 3, 5, 0, 4, 4, 1, 0, 0, 3597, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-5-2-1-2.json" :
TDATA[(2, 5, 2, 1, 2)] = \
    [1457, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 424, 0, 1, 0, 1]
# pulled from "tactics_work/kalah-results-2-5-2-1-3.json" :
TDATA[(2, 5, 2, 1, 3)] = \
    [1636, 2, 417, 0, 1631, 1, 9, 2, 1, 0, 4, 1, 1, 0, 0, 1457, 0, 1]
# pulled from "tactics_work/kalah-results-2-5-2-2-0.json" :
TDATA[(2, 5, 2, 2, 0)] = \
    [1602, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1337, 0, 1547]
# pulled from "tactics_work/kalah-results-2-5-2-2-1.json" :
TDATA[(2, 5, 2, 2, 1)] = \
    [2670, 1, 1, 519, 0, 2, 0, 1, 0, 2, 1, 1, 0, 0, 0, 1235, 1, 1985]
# pulled from "tactics_work/kalah-results-2-5-2-2-2.json" :
TDATA[(2, 5, 2, 2, 2)] = \
    [1, 974, 290, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1653, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-5-2-2-3.json" :
TDATA[(2, 5, 2, 2, 3)] = \
    [190, 3050, 2166, 1, 1261, 0, 1, 2, 3, 0, 2, 1, 0, 2, 1, 0, 842, 144]
# pulled from "tactics_work/kalah-results-2-5-3-0-0.json" :
TDATA[(2, 5, 3, 0, 0)] = \
    [1686, 1211, 2, 4173, 2, 699, 10, 5, 4, 4, 6, 3, 3373, 0, 0, 1876, 0, 187]
# pulled from "tactics_work/kalah-results-2-5-3-0-1.json" :
TDATA[(2, 5, 3, 0, 1)] = \
    [822, 244, 1550, 5818, 0, 3013, 10, 6, 1, 2, 2, 0, 1914, 863, 3913, 1011, 1878, 1234]
# pulled from "tactics_work/kalah-results-2-5-3-0-2.json" :
TDATA[(2, 5, 3, 0, 2)] = \
    [1455, 3171, 11952, 3, 2, 1, 7, 5, 2, 10, 4, 2, 0, 1307, 2977, 2234, 1021, 1822]
# pulled from "tactics_work/kalah-results-2-5-3-0-3.json" :
TDATA[(2, 5, 3, 0, 3)] = \
    [67, 2237, 1082, 416, 7461, 3311, 10, 1, 12, 1, 0, 1, 2236, 1019, 2, 3280, 3, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-0.json" :
TDATA[(2, 5, 3, 1, 0)] = \
    [1437, 2, 5191, 1147, 0, 2438, 5, 6, 2, 6, 7, 0, 4235, 3012, 8447, 1692, 3873, 4490]
# pulled from "tactics_work/kalah-results-2-5-3-1-1.json" :
TDATA[(2, 5, 3, 1, 1)] = \
    [5836, 1652, 614, 2173, 1, 2919, 0, 7, 11, 0, 4, 2, 0, 2705, 3578, 4, 491, 459]
# pulled from "tactics_work/kalah-results-2-5-3-1-2.json" :
TDATA[(2, 5, 3, 1, 2)] = \
    [2712, 2, 1055, 413, 859, 0, 2, 0, 0, 0, 2, 5, 3091, 33, 1422, 2, 1551, 4066]
# pulled from "tactics_work/kalah-results-2-5-3-1-3.json" :
TDATA[(2, 5, 3, 1, 3)] = \
    [2675, 0, 19, 279, 3360, 1, 0, 2, 4, 2, 1, 2, 0, 1359, 1, 0, 1639, 499]
# pulled from "tactics_work/kalah-results-2-5-3-2-0.json" :
TDATA[(2, 5, 3, 2, 0)] = \
    [4700, 5631, 0, 0, 1, 0, 17, 4, 2, 5, 9, 6, 7336, 4008, 1, 20, 4879, 442]
# pulled from "tactics_work/kalah-results-2-5-3-2-1.json" :
TDATA[(2, 5, 3, 2, 1)] = \
    [2175, 995, 798, 244, 2, 2, 5, 5, 0, 4, 9, 0, 4298, 5399, 1149, 3309, 1, 2092]
# pulled from "tactics_work/kalah-results-2-5-3-2-2.json" :
TDATA[(2, 5, 3, 2, 2)] = \
    [3552, 1011, 886, 4604, 3035, 0, 2, 1, 2, 2, 3, 5, 307, 2556, 7240, 1, 1899, 1810]
# pulled from "tactics_work/kalah-results-2-5-3-2-3.json" :
TDATA[(2, 5, 3, 2, 3)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 0, 0)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 0, 1)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 0, 2)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 0, 3)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 1, 0)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 1, 1)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 1, 2)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 1, 3)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 2, 0)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 2, 1)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 2, 2)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# file missing; repeating content :
TDATA[(2, 5, 4, 2, 3)] = \
    [0, 758, 0, 4463, 706, 4899, 5, 8, 12, 7, 5, 3, 1654, 1801, 0, 958, 4287, 1]
# pulled from "tactics_work/kalah-results-2-6-1-0-0.json" :
TDATA[(2, 6, 1, 0, 0)] = \
    [0, 2703, 1371, 4081, 501, 3731, 1, 4, 4, 0, 2, 10, 0, 1075, 2039, 2244, 1553, 989]
# pulled from "tactics_work/kalah-results-2-6-1-0-1.json" :
TDATA[(2, 6, 1, 0, 1)] = \
    [2, 4856, 1659, 0, 1002, 1109, 13, 2, 3, 8, 1, 4, 350, 0, 0, 0, 234, 2034]
# pulled from "tactics_work/kalah-results-2-6-1-0-2.json" :
TDATA[(2, 6, 1, 0, 2)] = \
    [4247, 1, 3938, 497, 745, 0, 12, 0, 5, 1, 1, 1, 189, 2149, 668, 0, 0, 1869]
# pulled from "tactics_work/kalah-results-2-6-1-0-3.json" :
TDATA[(2, 6, 1, 0, 3)] = \
    [260, 1676, 2575, 1713, 0, 2944, 2, 0, 0, 4, 2, 0, 1563, 562, 976, 1711, 806, 1]
# pulled from "tactics_work/kalah-results-2-6-1-1-0.json" :
TDATA[(2, 6, 1, 1, 0)] = \
    [1337, 4349, 2464, 0, 3, 1706, 6, 4, 3, 4, 1, 9, 2951, 0, 0, 0, 0, 301]
# pulled from "tactics_work/kalah-results-2-6-1-1-1.json" :
TDATA[(2, 6, 1, 1, 1)] = \
    [1, 2546, 692, 2, 5, 4779, 8, 1, 0, 0, 1, 8, 1, 0, 0, 1, 0, 2]
# pulled from "tactics_work/kalah-results-2-6-1-1-2.json" :
TDATA[(2, 6, 1, 1, 2)] = \
    [873, 1541, 552, 0, 1545, 1620, 1, 6, 6, 4, 1, 0, 2, 212, 703, 2, 388, 389]
# pulled from "tactics_work/kalah-results-2-6-1-1-3.json" :
TDATA[(2, 6, 1, 1, 3)] = \
    [8119, 4775, 0, 1592, 369, 0, 2, 5, 0, 2, 0, 9, 1299, 2093, 1, 433, 0, 1646]
# pulled from "tactics_work/kalah-results-2-6-1-2-0.json" :
TDATA[(2, 6, 1, 2, 0)] = \
    [5700, 2511, 2, 3574, 175, 1749, 11, 1, 8, 2, 15, 1, 2, 2, 0, 2, 1481, 679]
# pulled from "tactics_work/kalah-results-2-6-1-2-1.json" :
TDATA[(2, 6, 1, 2, 1)] = \
    [0, 1, 3300, 111, 296, 2484, 9, 6, 1, 4, 3, 4, 5369, 4, 2, 1794, 0, 1976]
# pulled from "tactics_work/kalah-results-2-6-1-2-2.json" :
TDATA[(2, 6, 1, 2, 2)] = \
    [1660, 2240, 5284, 2976, 0, 2466, 9, 9, 2, 15, 9, 4, 2597, 1, 588, 3945, 1141, 3403]
# pulled from "tactics_work/kalah-results-2-6-1-2-3.json" :
TDATA[(2, 6, 1, 2, 3)] = \
    [2069, 4, 3, 1259, 2, 1737, 1, 1, 3, 13, 0, 10, 6880, 3652, 0, 2421, 5805, 0]
# pulled from "tactics_work/kalah-results-2-6-2-0-0.json" :
TDATA[(2, 6, 2, 0, 0)] = \
    [2015, 1, 1639, 1, 1, 0, 1, 1, 1, 2, 2, 3, 1, 403, 1, 1, 1, 1332]
# pulled from "tactics_work/kalah-results-2-6-2-0-1.json" :
TDATA[(2, 6, 2, 0, 1)] = \
    [0, 0, 1982, 1, 1, 1769, 0, 1, 3, 0, 5, 1, 1, 1, 0, 896, 0, 10]
# pulled from "tactics_work/kalah-results-2-6-2-0-2.json" :
TDATA[(2, 6, 2, 0, 2)] = \
    [1, 0, 0, 2, 1, 1, 1, 3, 4, 1, 1, 0, 1, 1, 1736, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-6-2-0-3.json" :
TDATA[(2, 6, 2, 0, 3)] = \
    [2, 74, 1, 1, 0, 1636, 4, 1, 1, 2, 1, 6, 1, 1, 1, 1, 452, 2]
# pulled from "tactics_work/kalah-results-2-6-2-1-0.json" :
TDATA[(2, 6, 2, 1, 0)] = \
    [1, 2, 1380, 0, 1, 182, 1, 4, 2, 0, 2, 1, 0, 1, 2, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-6-2-1-1.json" :
TDATA[(2, 6, 2, 1, 1)] = \
    [1673, 2, 0, 0, 1, 2, 2, 4, 1, 0, 1, 0, 1, 2, 2, 2, 1092, 1964]
# pulled from "tactics_work/kalah-results-2-6-2-1-2.json" :
TDATA[(2, 6, 2, 1, 2)] = \
    [1, 1, 97, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]
# pulled from "tactics_work/kalah-results-2-6-2-1-3.json" :
TDATA[(2, 6, 2, 1, 3)] = \
    [0, 0, 1, 1, 1, 0, 5, 1, 0, 5, 1, 2, 2, 1, 1, 1433, 1, 1]
# pulled from "tactics_work/kalah-results-2-6-2-2-0.json" :
TDATA[(2, 6, 2, 2, 0)] = \
    [1, 275, 1, 1504, 1, 1554, 2, 1, 1, 1, 1, 5, 507, 1, 1, 2, 1, 1]
# pulled from "tactics_work/kalah-results-2-6-2-2-1.json" :
TDATA[(2, 6, 2, 2, 1)] = \
    [2, 1, 1, 1772, 86, 0, 1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 2284]
# pulled from "tactics_work/kalah-results-2-6-2-2-2.json" :
TDATA[(2, 6, 2, 2, 2)] = \
    [1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 329, 1]
# pulled from "tactics_work/kalah-results-2-6-2-2-3.json" :
TDATA[(2, 6, 2, 2, 3)] = \
    [1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1430, 0, 749]
# pulled from "tactics_work/kalah-results-2-6-3-0-0.json" :
TDATA[(2, 6, 3, 0, 0)] = \
    [0, 133, 0, 1317, 1939, 5045, 8, 2, 10, 3, 0, 2, 6584, 86, 2593, 2366, 941, 0]
# pulled from "tactics_work/kalah-results-2-6-3-0-1.json" :
TDATA[(2, 6, 3, 0, 1)] = \
    [5313, 2, 1, 0, 3305, 132, 2, 4, 0, 5, 1, 1, 218, 0, 0, 0, 497, 0]
# pulled from "tactics_work/kalah-results-2-6-3-0-2.json" :
TDATA[(2, 6, 3, 0, 2)] = \
    [5355, 3, 0, 3213, 2844, 1, 0, 2, 8, 0, 2, 3, 30, 503, 259, 1706, 620, 3]
# pulled from "tactics_work/kalah-results-2-6-3-0-3.json" :
TDATA[(2, 6, 3, 0, 3)] = \
    [593, 1, 2691, 290, 2057, 1043, 3, 4, 6, 4, 6, 2, 3743, 2560, 1044, 2104, 1436, 986]
# pulled from "tactics_work/kalah-results-2-6-3-1-0.json" :
TDATA[(2, 6, 3, 1, 0)] = \
    [513, 1, 1, 1094, 303, 3164, 5, 3, 3, 4, 1, 7, 1406, 1856, 2, 1860, 1882, 1]
# pulled from "tactics_work/kalah-results-2-6-3-1-1.json" :
TDATA[(2, 6, 3, 1, 1)] = \
    [2144, 5015, 1155, 848, 1808, 1708, 1, 6, 8, 1, 3, 2, 2477, 749, 1723, 5273, 3539, 2]
# pulled from "tactics_work/kalah-results-2-6-3-1-2.json" :
TDATA[(2, 6, 3, 1, 2)] = \
    [0, 1, 3262, 299, 1629, 3414, 14, 6, 2, 2, 5, 3, 4885, 6033, 2674, 0, 1994, 1681]
# pulled from "tactics_work/kalah-results-2-6-3-1-3.json" :
TDATA[(2, 6, 3, 1, 3)] = \
    [921, 3225, 405, 4080, 7847, 1199, 5, 1, 4, 3, 1, 5, 2253, 2952, 2057, 4346, 719, 1949]
# pulled from "tactics_work/kalah-results-2-6-3-2-0.json" :
TDATA[(2, 6, 3, 2, 0)] = \
    [4500, 1841, 11514, 3812, 1319, 1701, 2, 5, 0, 5, 1, 3, 3959, 1985, 6302, 7000, 2, 3254]
# pulled from "tactics_work/kalah-results-2-6-3-2-1.json" :
TDATA[(2, 6, 3, 2, 1)] = \
    [3620, 2883, 1900, 2467, 1765, 2241, 0, 9, 3, 1, 6, 3, 4, 3517, 4594, 167, 1222, 1]
# pulled from "tactics_work/kalah-results-2-6-3-2-2.json" :
TDATA[(2, 6, 3, 2, 2)] = \
    [5681, 0, 3, 148, 2, 0, 0, 4, 6, 2, 0, 3, 2, 1427, 3211, 1741, 0, 2]
# pulled from "tactics_work/kalah-results-2-6-3-2-3.json" :
TDATA[(2, 6, 3, 2, 3)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 0, 0)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 0, 1)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 0, 2)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 0, 3)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 1, 0)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 1, 1)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 1, 2)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 1, 3)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 2, 0)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 2, 1)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 2, 2)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]
# file missing; repeating content :
TDATA[(2, 6, 4, 2, 3)] = \
    [901, 5709, 2674, 1, 6, 2569, 2, 5, 3, 1, 6, 10, 2547, 0, 1, 3068, 3959, 0]

# DO NOT EDIT: autogenerated by "apply_tactics_generated.py"
