# autogenerated Tactics file
#

# header (containing the class and other items)
#
class Tactics(object):
    def __init__(self):
        self.empty_pit_value = [
            [1, 1], # 0 = nearest to STORE, (empty/empty, empty/full)
            [1, 1],  # 1    first value is value for empty; second is multiplier
            [1, 1],  # 2
            [1, 1],  # 3
            [1, 1],  # 4
            [1, 1],  # 5
        ]
        self.easy_repeat_value = [
            1, # pit 0 from store
            1, # 
            1, # 
            1, # 
            1, # 
            1, # 
        ]

#
# autogenerated portion:
#
#### START AUTOGEN ####
