# DO NOT EDIT: autogenerated by "apply_tactics_generated.py"

TDATA = {}
# pulled from "tactics_work/kalah-results-1-4-0-0-0.json" :
TDATA[(1, 4, 0, 0, 0)] = \
    [0, 0, 0, 0, 0, -1621, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-0-0-1.json" :
TDATA[(1, 4, 0, 0, 1)] = \
    [-2, 0, 1198, 0, -1265, -1201, -2, 0, 0, 1, 3, 3, 0, 84, -1746, 0, 0, -506]
# pulled from "tactics_work/kalah-results-1-4-0-0-2.json" :
TDATA[(1, 4, 0, 0, 2)] = \
    [1, -369, 0, -466, 1063, -351, 2, 0, 0, 0, 0, -1, 0, -185, 0, -156, 1784, 0]
# pulled from "tactics_work/kalah-results-1-4-0-0-3.json" :
TDATA[(1, 4, 0, 0, 3)] = \
    [-258, 959, -649, 1190, -762, 565, 0, 0, -1, 4, 2, 0, -172, -1028, -1442, 868, 0, -1763]
# pulled from "tactics_work/kalah-results-1-4-0-1-0.json" :
TDATA[(1, 4, 0, 1, 0)] = \
    [1644, 0, 0, 1, 0, -998, 0, -1, 5, 1, -1, 0, 1, 0, 0, -1164, 1218, 0]
# pulled from "tactics_work/kalah-results-1-4-0-1-1.json" :
TDATA[(1, 4, 0, 1, 1)] = \
    [0, -1, 0, -1756, 0, 0, 1, 0, -1, 0, 2, 0, -1, -1412, 0, 0, 1636, -1]
# pulled from "tactics_work/kalah-results-1-4-0-1-2.json" :
TDATA[(1, 4, 0, 1, 2)] = \
    [0, -1651, 1, 0, 18, 1226, 0, 0, 0, 0, 2, 4, 0, 1, 1330, 0, 1272, -1]
# pulled from "tactics_work/kalah-results-1-4-0-1-3.json" :
TDATA[(1, 4, 0, 1, 3)] = \
    [-659, 1885, 0, 1680, 1, 1737, 1, -2, -1, 1, -1, -4, 0, 1344, 0, -1256, 1, -2766]
# pulled from "tactics_work/kalah-results-1-4-0-2-0.json" :
TDATA[(1, 4, 0, 2, 0)] = \
    [0, 0, -1453, 0, -2, 0, 0, 0, 0, 0, 0, 0, -638, 0, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-1-4-0-2-1.json" :
TDATA[(1, 4, 0, 2, 1)] = \
    [1478, 0, 0, 0, 0, -1872, 0, -2, 0, -8, -5, 0, 0, 0, 0, 2914, 0, -1]
# pulled from "tactics_work/kalah-results-1-4-0-2-2.json" :
TDATA[(1, 4, 0, 2, 2)] = \
    [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1497, 1935, 2839, 1, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-0-2-3.json" :
TDATA[(1, 4, 0, 2, 3)] = \
    [0, 0, -1, 0, 0, 0, 0, 2, 0, 0, 0, 0, -682, 0, 0, 0, 0, -1595]
# pulled from "tactics_work/kalah-results-1-4-3-0-0.json" :
TDATA[(1, 4, 3, 0, 0)] = \
    [-555, 731, -1735, 0, 0, 919, 3, 0, 3, -3, -1, 1, 1029, 1, 1894, -1069, 2, 0]
# pulled from "tactics_work/kalah-results-1-4-3-0-1.json" :
TDATA[(1, 4, 3, 0, 1)] = \
    [-2572, 0, -1907, 0, 0, -618, -1, 0, -2, 4, -1, -1, 1, 0, -1079, 1042, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-0-2.json" :
TDATA[(1, 4, 3, 0, 2)] = \
    [1, 0, -1837, 0, -1134, -1825, 0, 0, 4, 1, 0, 0, -2, -327, -289, 0, 622, 1]
# pulled from "tactics_work/kalah-results-1-4-3-0-3.json" :
TDATA[(1, 4, 3, 0, 3)] = \
    [0, 990, 1, -1134, -1051, -1747, 3, -3, 0, 0, -3, 4, 2, 951, 1979, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-0.json" :
TDATA[(1, 4, 3, 1, 0)] = \
    [0, 0, 1, -1488, -1, 0, 0, 0, 0, 0, 1, 0, -326, -725, 0, 1446, -2, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-1.json" :
TDATA[(1, 4, 3, 1, 1)] = \
    [0, -1, 1639, 0, -997, 1, 0, -1, 0, -5, 0, 0, 1, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-2.json" :
TDATA[(1, 4, 3, 1, 2)] = \
    [0, 167, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1179, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-4-3-1-3.json" :
TDATA[(1, 4, 3, 1, 3)] = \
    [0, 0, 0, -1, -877, 0, 1, 0, 0, 0, 0, 0, 1, 0, -1, 0, 0, -1]
# pulled from "tactics_work/kalah-results-1-4-3-2-0.json" :
TDATA[(1, 4, 3, 2, 0)] = \
    [2973, 1, 0, -894, 0, 0, -1, 0, 0, 0, 0, 0, 0, 1, -1324, 1, 1, 1687]
# pulled from "tactics_work/kalah-results-1-4-3-2-1.json" :
TDATA[(1, 4, 3, 2, 1)] = \
    [-345, -831, 0, -1, 1, 162, 0, 4, 1, 0, -3, 6, 1152, 0, 0, 0, 715, 2]
# pulled from "tactics_work/kalah-results-1-4-3-2-2.json" :
TDATA[(1, 4, 3, 2, 2)] = \
    [1, -829, -38, -57, -2, 0, 1, 1, -1, 0, 1, -1, 0, 758, 0, 0, -550, 0]
# pulled from "tactics_work/kalah-results-1-4-3-2-3.json" :
TDATA[(1, 4, 3, 2, 3)] = \
    [1, 1256, 1006, -2749, 0, 1241, -1, 0, -1, -4, 0, 0, 0, 0, 0, 0, 1094, 1]
# pulled from "tactics_work/kalah-results-1-3-0-0-0.json" :
TDATA[(1, 3, 0, 0, 0)] = \
    [0, -1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, -1441, 0]
# pulled from "tactics_work/kalah-results-1-3-0-0-1.json" :
TDATA[(1, 3, 0, 0, 1)] = \
    [0, 0, 0, -1, 0, 0, -3, 0, 2, -1, 0, 0, 208, 1478, 270, 0, -1010, -1224]
# pulled from "tactics_work/kalah-results-1-3-0-0-2.json" :
TDATA[(1, 3, 0, 0, 2)] = \
    [0, 0, 583, -1, 1155, 0, 0, 0, 0, -1, 0, 0, 0, 0, -370, 1078, 673, 0]
# pulled from "tactics_work/kalah-results-1-3-0-0-3.json" :
TDATA[(1, 3, 0, 0, 3)] = \
    [0, -347, 0, -228, 0, 0, 0, -1, 0, 1, 0, 0, 0, -258, 0, -358, 0, -2593]
# pulled from "tactics_work/kalah-results-1-3-0-1-0.json" :
TDATA[(1, 3, 0, 1, 0)] = \
    [919, -920, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1299, 0, -1548, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-0-1-1.json" :
TDATA[(1, 3, 0, 1, 1)] = \
    [-347, 1967, 967, 2, -1888, 0, 1, 2, 1, 0, -1, 0, 1220, 1978, -2148, 0, 1, -1]
# pulled from "tactics_work/kalah-results-1-3-0-1-2.json" :
TDATA[(1, 3, 0, 1, 2)] = \
    [-640, -775, 0, -1086, 1411, 0, -2, 0, 0, -3, -1, 0, 1, 0, 1507, -1706, 0, 246]
# pulled from "tactics_work/kalah-results-1-3-0-1-3.json" :
TDATA[(1, 3, 0, 1, 3)] = \
    [0, 0, -2237, 0, 0, 0, 0, -2, 7, 0, -1, -2, -1, 0, 493, 1256, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-0-2-0.json" :
TDATA[(1, 3, 0, 2, 0)] = \
    [-2858, 1, 2, -652, 977, -387, -1, -7, -1, -2, -5, 0, -997, -1624, 4198, 1053, 2, -1557]
# pulled from "tactics_work/kalah-results-1-3-0-2-1.json" :
TDATA[(1, 3, 0, 2, 1)] = \
    [3427, 1, 1, 0, 502, 0, 1, 0, 0, -5, 0, 4, -1, 1882, 402, 0, 0, 1684]
# pulled from "tactics_work/kalah-results-1-3-0-2-2.json" :
TDATA[(1, 3, 0, 2, 2)] = \
    [103, -107, 0, 0, 0, 1, -4, -1, -1, 0, 0, 0, 0, 0, -1909, 1, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-0-2-3.json" :
TDATA[(1, 3, 0, 2, 3)] = \
    [1268, -239, 1, 1461, 0, 2298, -1, 1, 1, 3, 3, 1, 1265, -1, -2301, 0, 0, 1537]
# pulled from "tactics_work/kalah-results-1-3-3-0-0.json" :
TDATA[(1, 3, 3, 0, 0)] = \
    [0, 0, 1, -1351, -1445, 1618, -1, 3, 4, -3, 0, 0, 0, 1, -2, 2050, 0, 544]
# pulled from "tactics_work/kalah-results-1-3-3-0-1.json" :
TDATA[(1, 3, 3, 0, 1)] = \
    [0, 0, 848, 0, 0, 1875, 3, 0, -1, 1, 0, 0, -1051, -980, -285, 1, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-3-0-2.json" :
TDATA[(1, 3, 3, 0, 2)] = \
    [0, 1, -1806, 0, 0, 1303, 1, 2, 0, -2, 4, 0, 0, 1142, -347, 1, 0, 1]
# pulled from "tactics_work/kalah-results-1-3-3-0-3.json" :
TDATA[(1, 3, 3, 0, 3)] = \
    [0, 0, 122, 0, 1, 0, 4, 0, 1, 0, 3, -4, -1947, -1420, 1884, 0, -1, 1590]
# pulled from "tactics_work/kalah-results-1-3-3-1-0.json" :
TDATA[(1, 3, 3, 1, 0)] = \
    [0, 0, 0, 0, -1, 1867, 1, -1, 0, -1, 1, 0, -1, 0, 0, -1708, -1, -49]
# pulled from "tactics_work/kalah-results-1-3-3-1-1.json" :
TDATA[(1, 3, 3, 1, 1)] = \
    [-1973, 0, 876, -631, 0, 375, 0, -2, 1, 0, 1, 0, 1655, 0, 0, 1, -1, 0]
# pulled from "tactics_work/kalah-results-1-3-3-1-2.json" :
TDATA[(1, 3, 3, 1, 2)] = \
    [0, 0, -814, 0, 0, 0, 0, 0, -1, 0, 0, 2, 0, 1, 0, 0, -1519, 0]
# pulled from "tactics_work/kalah-results-1-3-3-1-3.json" :
TDATA[(1, 3, 3, 1, 3)] = \
    [0, 1611, 0, -1, 0, 0, 0, 0, 0, 0, 0, 3, 289, 0, 1263, 2, -1512, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-0.json" :
TDATA[(1, 3, 3, 2, 0)] = \
    [0, 1, 0, 0, 0, 0, -1, 0, -4, -1, 0, 3, 0, 1142, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-1.json" :
TDATA[(1, 3, 3, 2, 1)] = \
    [1, 0, 0, 855, 1, 1, 0, 1, 0, -3, 0, 0, -1498, 1, -1, 0, 1, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-2.json" :
TDATA[(1, 3, 3, 2, 2)] = \
    [0, 0, 0, 0, 1, 0, 1, 0, 0, -3, 0, -4, 0, 0, 573, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-3-3-2-3.json" :
TDATA[(1, 3, 3, 2, 3)] = \
    [0, 0, 1, 1, 582, 0, 0, 1, 4, -4, 1, -2, 1, 0, 0, 0, -577, -362]
# pulled from "tactics_work/kalah-results-1-5-0-0-0.json" :
TDATA[(1, 5, 0, 0, 0)] = \
    [-4, 200, 1748, 0, -1794, 1285, 2, 0, -4, 0, 0, -2, -1993, 0, -1220, 269, -730, 1709]
# pulled from "tactics_work/kalah-results-1-5-0-0-1.json" :
TDATA[(1, 5, 0, 0, 1)] = \
    [0, -1290, 1, 1684, 0, 178, 0, 0, -2, 1, -2, 3, -1063, 0, -1520, 1591, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-0-0-2.json" :
TDATA[(1, 5, 0, 0, 2)] = \
    [1, -1, 0, 503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1474]
# pulled from "tactics_work/kalah-results-1-5-0-0-3.json" :
TDATA[(1, 5, 0, 0, 3)] = \
    [-1171, 0, 0, 1564, -3452, 1144, 5, 0, 1, 1, -3, 0, -2920, -872, 868, 1, 861, 1167]
# pulled from "tactics_work/kalah-results-1-5-0-1-0.json" :
TDATA[(1, 5, 0, 1, 0)] = \
    [0, 1, 1222, 1979, -830, 0, 0, 1, -1, 1, 0, -4, 981, 0, 2830, 1, 1296, 1233]
# pulled from "tactics_work/kalah-results-1-5-0-1-1.json" :
TDATA[(1, 5, 0, 1, 1)] = \
    [-623, -1114, 0, 0, 484, 0, -4, 0, -3, 4, -1, 0, 0, 0, 117, 1871, 1, -1]
# pulled from "tactics_work/kalah-results-1-5-0-1-2.json" :
TDATA[(1, 5, 0, 1, 2)] = \
    [1540, 1, 665, -397, 183, 1776, 0, 6, 4, 0, -2, -1, -1542, 1300, -863, 0, 1256, 1699]
# pulled from "tactics_work/kalah-results-1-5-0-1-3.json" :
TDATA[(1, 5, 0, 1, 3)] = \
    [-1, 1, 1749, 0, -1711, -636, -2, 0, -1, -1, -5, 3, 1581, -709, -708, -461, 1666, 1838]
# pulled from "tactics_work/kalah-results-1-5-0-2-0.json" :
TDATA[(1, 5, 0, 2, 0)] = \
    [0, 0, 1, 1731, 1121, 0, 0, 3, 0, 0, 0, 1, 0, 1, -27, -1146, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-0-2-1.json" :
TDATA[(1, 5, 0, 2, 1)] = \
    [0, 0, -941, 0, -1796, 1, 4, 0, 4, 0, 0, 1, 1191, 1, 0, 0, -2958, -1]
# pulled from "tactics_work/kalah-results-1-5-0-2-2.json" :
TDATA[(1, 5, 0, 2, 2)] = \
    [47, 0, 0, 1, 815, 3355, 0, 1, 0, 1, 0, 0, 463, -1, 0, 516, 299, 0]
# pulled from "tactics_work/kalah-results-1-5-0-2-3.json" :
TDATA[(1, 5, 0, 2, 3)] = \
    [1173, 1682, -2820, 1, -612, -2, 0, -1, 2, 0, -1, 7, 0, -399, 1, 1792, -1409, -177]
# pulled from "tactics_work/kalah-results-1-5-3-0-0.json" :
TDATA[(1, 5, 3, 0, 0)] = \
    [-1435, 1, 2, 326, -1, -1, -2, 4, 0, -1, 0, -2, -1069, 285, 0, -1, -2, 0]
# pulled from "tactics_work/kalah-results-1-5-3-0-1.json" :
TDATA[(1, 5, 3, 0, 1)] = \
    [0, 0, 0, 0, 1934, -1, 0, 1, 0, 2, 3, 0, 0, 0, 0, 1, -1, -1]
# pulled from "tactics_work/kalah-results-1-5-3-0-2.json" :
TDATA[(1, 5, 3, 0, 2)] = \
    [1, 0, 0, 0, 1981, 206, -1, 0, -1, 1, 0, 1, -2, 0, -145, 1143, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-0-3.json" :
TDATA[(1, 5, 3, 0, 3)] = \
    [0, -1750, -421, 0, 0, -1, 1, 0, 0, 0, 2, -1, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-1-0.json" :
TDATA[(1, 5, 3, 1, 0)] = \
    [1, 608, 0, 0, 0, -1449, -1, 0, 0, 0, 0, -5, 1428, -2778, 0, 0, -1, -1]
# pulled from "tactics_work/kalah-results-1-5-3-1-1.json" :
TDATA[(1, 5, 3, 1, 1)] = \
    [1, 0, -1555, 0, -1052, 1, 3, -3, -4, 0, -4, 0, 0, -1696, 1745, 1689, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-1-2.json" :
TDATA[(1, 5, 3, 1, 2)] = \
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-1-5-3-1-3.json" :
TDATA[(1, 5, 3, 1, 3)] = \
    [1, 0, -1965, -1403, 0, 0, 0, 0, 2, 0, 0, 0, 0, -523, -905, -1, 0, 0]
# pulled from "tactics_work/kalah-results-1-5-3-2-0.json" :
TDATA[(1, 5, 3, 2, 0)] = \
    [0, 0, 0, 0, 0, 0, 1, 1, 0, -1, 0, 1, 1524, 0, 0, -743, -326, 0]
# pulled from "tactics_work/kalah-results-1-5-3-2-1.json" :
TDATA[(1, 5, 3, 2, 1)] = \
    [-1, 2, -939, -170, 563, 0, 1, 0, -2, -1, 0, 0, -1, -823, -2536, 0, -495, 271]
# pulled from "tactics_work/kalah-results-1-5-3-2-2.json" :
TDATA[(1, 5, 3, 2, 2)] = \
    [-1, 0, -2, 1, 189, 1, 1, -3, 0, -7, 0, 1, -682, 1, -1, 0, -1141, -1157]
# pulled from "tactics_work/kalah-results-1-5-3-2-3.json" :
TDATA[(1, 5, 3, 2, 3)] = \
    [0, -1094, 1, 0, -1, -1547, 3, 1, 0, -2, 1, 0, 0, 0, -1400, 1201, 1710, 0]
# pulled from "tactics_work/kalah-results-1-6-0-0-0.json" :
TDATA[(1, 6, 0, 0, 0)] = \
    [0, 0, 1, 0, 1, -1, 0, -4, -4, 0, 0, 2, -1, 0, 0, 1, -750, -1933]
# pulled from "tactics_work/kalah-results-1-6-0-0-1.json" :
TDATA[(1, 6, 0, 0, 1)] = \
    [464, 0, 0, 0, 0, 0, 0, -2, 0, 2, 0, -1, 0, 1, 3160, 0, 0, 1179]
# pulled from "tactics_work/kalah-results-1-6-0-0-2.json" :
TDATA[(1, 6, 0, 0, 2)] = \
    [1382, -526, 1, 0, 452, 1, -2, 2, -4, -1, 0, -3, 0, -1, 0, 0, 0, 2]
# pulled from "tactics_work/kalah-results-1-6-0-0-3.json" :
TDATA[(1, 6, 0, 0, 3)] = \
    [0, 157, 1499, -392, 1560, 0, 0, 1, 0, -1, 0, -1, 828, 1862, 0, -1926, 1416, -58]
# pulled from "tactics_work/kalah-results-1-6-0-1-0.json" :
TDATA[(1, 6, 0, 1, 0)] = \
    [1334, -2, 1731, 0, 0, -1543, -1, 0, 1, 0, -2, 4, -30, -1770, 1941, -1, 0, -2802]
# pulled from "tactics_work/kalah-results-1-6-0-1-1.json" :
TDATA[(1, 6, 0, 1, 1)] = \
    [621, -1306, -1, -505, 4709, 1, 5, 0, -4, 0, -1, 2, 652, 106, 1095, -402, 845, 0]
# pulled from "tactics_work/kalah-results-1-6-0-1-2.json" :
TDATA[(1, 6, 0, 1, 2)] = \
    [1073, 125, 1, -1455, -1857, -1628, -3, 0, 1, 0, -1, 2, -217, 1, -113, 1, -458, 1]
# pulled from "tactics_work/kalah-results-1-6-0-1-3.json" :
TDATA[(1, 6, 0, 1, 3)] = \
    [0, -1950, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, -1312]
# pulled from "tactics_work/kalah-results-1-6-0-2-0.json" :
TDATA[(1, 6, 0, 2, 0)] = \
    [840, 0, -646, -1, 0, 0, 0, -2, 0, 0, 0, 0, 0, -2, 0, -1, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-0-2-1.json" :
TDATA[(1, 6, 0, 2, 1)] = \
    [0, 0, -1, 0, 0, 0, 0, -3, 0, 0, 0, 0, 1817, 0, -1, -1648, 90, 0]
# pulled from "tactics_work/kalah-results-1-6-0-2-2.json" :
TDATA[(1, 6, 0, 2, 2)] = \
    [0, 0, 0, -1658, -956, 0, 0, 0, 1, -1, -2, 0, 0, 416, 1457, 807, 0, 330]
# pulled from "tactics_work/kalah-results-1-6-0-2-3.json" :
TDATA[(1, 6, 0, 2, 3)] = \
    [1045, 0, -2, 0, -1961, 1579, 1, 0, -3, 3, 1, 8, 2590, -367, 1381, -808, 1904, 0]
# pulled from "tactics_work/kalah-results-1-6-3-0-0.json" :
TDATA[(1, 6, 3, 0, 0)] = \
    [0, 0, 0, 0, 0, -1545, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-0-1.json" :
TDATA[(1, 6, 3, 0, 1)] = \
    [-1452, 963, 1140, 344, 389, 1705, 1, 1, -1, -1, 4, 0, 0, -1, 779, -1, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-0-2.json" :
TDATA[(1, 6, 3, 0, 2)] = \
    [0, 0, -499, 0, 0, -747, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-0-3.json" :
TDATA[(1, 6, 3, 0, 3)] = \
    [422, 0, 251, 89, 0, -1, 1, 0, 0, 0, -1, -2, -1650, 0, -1, 0, 0, 1]
# pulled from "tactics_work/kalah-results-1-6-3-1-0.json" :
TDATA[(1, 6, 3, 1, 0)] = \
    [3, -787, 1586, 0, 0, 1505, -1, 0, 4, -7, 1, 1, -1, 0, 1171, -2558, -1117, -977]
# pulled from "tactics_work/kalah-results-1-6-3-1-1.json" :
TDATA[(1, 6, 3, 1, 1)] = \
    [1141, 0, 0, 0, 0, 0, -1, 1, 0, 0, -2, 0, 1, -1, 1961, 0, 0, 1629]
# pulled from "tactics_work/kalah-results-1-6-3-1-2.json" :
TDATA[(1, 6, 3, 1, 2)] = \
    [-1, 0, -780, 1852, -488, -1, 4, 1, 0, 5, 1, -2, 1, 306, 665, -1, 0, 1579]
# pulled from "tactics_work/kalah-results-1-6-3-1-3.json" :
TDATA[(1, 6, 3, 1, 3)] = \
    [0, 0, 1047, 0, 173, 1, 1, 0, 0, 0, 0, 0, 1921, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-2-0.json" :
TDATA[(1, 6, 3, 2, 0)] = \
    [0, 1815, 0, 0, 0, 0, 0, 0, -2, -1, 0, 0, 0, 1586, 472, 0, 0, 0]
# pulled from "tactics_work/kalah-results-1-6-3-2-1.json" :
TDATA[(1, 6, 3, 2, 1)] = \
    [0, 0, -1091, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, -5, 1193]
# pulled from "tactics_work/kalah-results-1-6-3-2-2.json" :
TDATA[(1, 6, 3, 2, 2)] = \
    [-907, 0, -1, 0, 1311, 0, 0, 2, 4, 0, 0, 1, 0, 841, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-1-6-3-2-3.json" :
TDATA[(1, 6, 3, 2, 3)] = \
    [1529, 0, 389, 0, 0, 827, -1, -1, 0, 0, -1, 0, 0, 0, -1144, 2364, -1049, 0]
# pulled from "tactics_work/kalah-results-2-4-0-0-0.json" :
TDATA[(2, 4, 0, 0, 0)] = \
    [-703, 0, 0, 1534, 1842, -1, -3, 1, 1, 0, 1, -1, 465, -1445, 0, 1066, 0, -1331]
# pulled from "tactics_work/kalah-results-2-4-0-0-1.json" :
TDATA[(2, 4, 0, 0, 1)] = \
    [610, 0, 0, 811, 513, -965, 0, 0, -1, 1, -4, 0, -3688, 333, 0, 0, 0, -893]
# pulled from "tactics_work/kalah-results-2-4-0-0-2.json" :
TDATA[(2, 4, 0, 0, 2)] = \
    [-740, 1, -1085, 1753, 0, 1, 0, -8, 4, 0, 3, 1, 1602, 0, -1540, 0, 0, -647]
# pulled from "tactics_work/kalah-results-2-4-0-0-3.json" :
TDATA[(2, 4, 0, 0, 3)] = \
    [1738, 0, 0, 1155, 1, 1444, 1, 0, -1, 0, 6, 0, 1478, -1, -2931, 0, -1, 0]
# pulled from "tactics_work/kalah-results-2-4-0-1-0.json" :
TDATA[(2, 4, 0, 1, 0)] = \
    [-700, 1, 1, -3723, 1113, -2581, -1, 5, 2, 1, -1, 3, 396, -1622, 1, 1415, 0, 927]
# pulled from "tactics_work/kalah-results-2-4-0-1-1.json" :
TDATA[(2, 4, 0, 1, 1)] = \
    [0, -1366, 0, 0, 1285, -1, 0, -2, -1, 0, 0, -3, 0, -956, -801, 0, 1965, -1461]
# pulled from "tactics_work/kalah-results-2-4-0-1-2.json" :
TDATA[(2, 4, 0, 1, 2)] = \
    [0, -1907, -1, -21, 0, 1854, 0, 0, -1, 0, 0, 0, 579, 1, 911, 239, 3752, 0]
# pulled from "tactics_work/kalah-results-2-4-0-1-3.json" :
TDATA[(2, 4, 0, 1, 3)] = \
    [0, 1881, 0, 0, 0, 0, -1, -1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-0-2-0.json" :
TDATA[(2, 4, 0, 2, 0)] = \
    [-314, -179, -1777, 1, -1, -1, 0, -1, 0, 6, 0, 0, 297, -1285, 0, 303, -562, -1]
# pulled from "tactics_work/kalah-results-2-4-0-2-1.json" :
TDATA[(2, 4, 0, 2, 1)] = \
    [0, 0, 0, -1191, 1, 919, 0, 0, 0, 0, 0, -1, 1993, 198, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-0-2-2.json" :
TDATA[(2, 4, 0, 2, 2)] = \
    [0, 1, 0, -1746, -1, -1, 0, 0, -2, 0, 3, 2, -1989, 1293, -1164, 1459, 1989, -2810]
# pulled from "tactics_work/kalah-results-2-4-0-2-3.json" :
TDATA[(2, 4, 0, 2, 3)] = \
    [0, 0, 0, 0, 0, 0, 0, 3, 0, -1, -1, -1, 0, -1, -348, 1200, 0, -1266]
# pulled from "tactics_work/kalah-results-2-4-3-0-0.json" :
TDATA[(2, 4, 3, 0, 0)] = \
    [0, 1702, 0, 0, 0, -1408, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-3-0-1.json" :
TDATA[(2, 4, 3, 0, 1)] = \
    [1749, 0, -1271, 1, -2019, -1422, -5, 0, 0, -4, 0, -2, 0, 0, 1328, 1369, 0, 0]
# pulled from "tactics_work/kalah-results-2-4-3-0-2.json" :
TDATA[(2, 4, 3, 0, 2)] = \
    [-1, 1996, -74, 0, 1, -1104, 1, -1, 0, 0, -3, 0, 0, -1, 0, 0, -1382, 0]
# pulled from "tactics_work/kalah-results-2-4-3-0-3.json" :
TDATA[(2, 4, 3, 0, 3)] = \
    [1377, -716, 0, 0, -1810, 0, 0, 0, 0, 0, 0, 1, 0, -1, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-2-4-3-1-0.json" :
TDATA[(2, 4, 3, 1, 0)] = \
    [-418, 1, 553, -2887, 0, 0, 0, 0, 2, 6, 0, -2, 0, 1, -2, -1727, 23, 0]
# pulled from "tactics_work/kalah-results-2-4-3-1-1.json" :
TDATA[(2, 4, 3, 1, 1)] = \
    [0, 1817, -644, -1, 1, 1153, -4, 0, 0, 0, 1, 0, 1, 1556, 1043, 513, 1, 0]
# pulled from "tactics_work/kalah-results-2-4-3-1-2.json" :
TDATA[(2, 4, 3, 1, 2)] = \
    [0, 1476, -2496, 429, 0, 1131, 0, -4, -4, -3, 0, 0, 126, 1621, 1818, 706, 1, 2282]
# pulled from "tactics_work/kalah-results-2-4-3-1-3.json" :
TDATA[(2, 4, 3, 1, 3)] = \
    [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, -911, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-0.json" :
TDATA[(2, 4, 3, 2, 0)] = \
    [1, 1190, 0, 0, 1440, -1, 3, 0, 1, 1, 2, 0, 1, 1198, -776, -1235, -969, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-1.json" :
TDATA[(2, 4, 3, 2, 1)] = \
    [2965, 1629, 0, -2, 0, 1822, 0, -1, 0, 0, -2, 4, 0, 0, -1039, 0, 1, 1]
# pulled from "tactics_work/kalah-results-2-4-3-2-2.json" :
TDATA[(2, 4, 3, 2, 2)] = \
    [0, 0, 1, 0, 0, 1894, 1, 0, -2, 2, 0, 0, 1, 0, 0, 0, -1, 0]
# pulled from "tactics_work/kalah-results-2-4-3-2-3.json" :
TDATA[(2, 4, 3, 2, 3)] = \
    [0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 847, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-0-0-0.json" :
TDATA[(2, 3, 0, 0, 0)] = \
    [1, 0, 0, -760, 1153, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 294, 1]
# pulled from "tactics_work/kalah-results-2-3-0-0-1.json" :
TDATA[(2, 3, 0, 0, 1)] = \
    [0, 0, 0, -794, 0, 0, 0, 0, 0, 0, -1, -1, 0, 934, 0, 1926, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-0-0-2.json" :
TDATA[(2, 3, 0, 0, 2)] = \
    [0, 0, -1877, -720, 467, 0, 0, 0, 0, -1, 1, 2, -1796, 1019, 581, -1, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-0-0-3.json" :
TDATA[(2, 3, 0, 0, 3)] = \
    [-483, 607, 0, 0, 873, 0, 3, 0, 0, 1, -1, 0, -97, 0, -1, 0, 329, -1665]
# pulled from "tactics_work/kalah-results-2-3-0-1-0.json" :
TDATA[(2, 3, 0, 1, 0)] = \
    [1, 1, 0, -794, -1, 1, -1, 7, 0, 0, 0, -1, 0, 1110, -1, -1470, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-0-1-1.json" :
TDATA[(2, 3, 0, 1, 1)] = \
    [-1, 0, 0, 0, 0, 0, 0, 0, 0, -4, 0, 3, -1, 0, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-2-3-0-1-2.json" :
TDATA[(2, 3, 0, 1, 2)] = \
    [1319, 0, 0, 0, 0, -1199, 0, 0, 1, 1, 1, 0, 1892, 0, 0, 789, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-0-1-3.json" :
TDATA[(2, 3, 0, 1, 3)] = \
    [-2443, 1969, -1779, 0, 818, 2499, 4, 0, -7, 6, -1, 1, 0, -2, 0, 3649, 0, 106]
# pulled from "tactics_work/kalah-results-2-3-0-2-0.json" :
TDATA[(2, 3, 0, 2, 0)] = \
    [0, 0, 0, 1640, 2520, 0, 0, 0, 1, 2, 7, 3, -1011, 1128, 2827, 0, -1456, -442]
# pulled from "tactics_work/kalah-results-2-3-0-2-1.json" :
TDATA[(2, 3, 0, 2, 1)] = \
    [-1882, 1, 0, -1562, 0, 0, 0, 0, 0, -3, 0, 6, -1092, 949, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-2-3-0-2-2.json" :
TDATA[(2, 3, 0, 2, 2)] = \
    [0, 0, 1, 0, 2036, -1166, 0, -4, -3, -2, 1, 1, 1463, 1, -758, 288, 1837, 1110]
# pulled from "tactics_work/kalah-results-2-3-0-2-3.json" :
TDATA[(2, 3, 0, 2, 3)] = \
    [0, -1, 1847, -348, 1396, -42, 1, 1, -1, 1, 0, 1, 1, 1957, -1206, -1, -1207, -1932]
# pulled from "tactics_work/kalah-results-2-3-3-0-0.json" :
TDATA[(2, 3, 3, 0, 0)] = \
    [3, 0, 0, -1856, 2, 1632, 1, 2, -2, -1, 0, 1, -912, 0, -1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-1.json" :
TDATA[(2, 3, 3, 0, 1)] = \
    [0, -3, 0, 0, -503, 1172, 1, 0, 1, 0, 0, 0, 2710, -1, 0, 1019, 1607, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-2.json" :
TDATA[(2, 3, 3, 0, 2)] = \
    [0, 1100, -1328, 0, 0, 1101, 1, 1, 0, 0, 0, 0, 147, 0, -1, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-0-3.json" :
TDATA[(2, 3, 3, 0, 3)] = \
    [-1810, 0, 0, 1, 0, 0, 1, 1, 0, -1, 0, 0, 0, -340, -1059, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-1-0.json" :
TDATA[(2, 3, 3, 1, 0)] = \
    [0, 0, 0, -1, 0, 1427, 4, -1, 0, 4, 0, -1, 0, 0, -1741, 0, -505, 0]
# pulled from "tactics_work/kalah-results-2-3-3-1-1.json" :
TDATA[(2, 3, 3, 1, 1)] = \
    [-1438, 0, -2, -1, -907, 0, 0, 2, 0, -2, 0, -4, 1261, 1306, 0, -654, 1327, -71]
# pulled from "tactics_work/kalah-results-2-3-3-1-2.json" :
TDATA[(2, 3, 3, 1, 2)] = \
    [0, 0, 242, -1343, -1213, 2296, 0, -2, -4, 0, 0, -1, 935, 0, 1, 0, 1003, 1]
# pulled from "tactics_work/kalah-results-2-3-3-1-3.json" :
TDATA[(2, 3, 3, 1, 3)] = \
    [-1, 0, -1249, -1, -1466, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 729]
# pulled from "tactics_work/kalah-results-2-3-3-2-0.json" :
TDATA[(2, 3, 3, 2, 0)] = \
    [0, -1321, -836, 231, 0, -624, -3, -1, 0, -1, 1, 0, 307, 0, 529, -140, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-2-1.json" :
TDATA[(2, 3, 3, 2, 1)] = \
    [-474, -1, 920, -1, 2359, 0, 0, -2, -1, 0, 3, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-3-3-2-2.json" :
TDATA[(2, 3, 3, 2, 2)] = \
    [-1760, -806, -1734, 973, -1669, -1, -4, -5, 3, 1, -3, 0, -1451, -1887, -407, 1021, -2, 0]
# pulled from "tactics_work/kalah-results-2-3-3-2-3.json" :
TDATA[(2, 3, 3, 2, 3)] = \
    [0, -1450, 208, -2, 0, 1323, 0, 0, 0, 0, 0, 0, -2, -282, -1, -1, 504, 0]
# pulled from "tactics_work/kalah-results-2-5-0-0-0.json" :
TDATA[(2, 5, 0, 0, 0)] = \
    [0, 0, 0, 0, 1626, 1, 0, 0, 0, 0, 0, 0, 0, 0, 421, -402, 0, 1878]
# pulled from "tactics_work/kalah-results-2-5-0-0-1.json" :
TDATA[(2, 5, 0, 0, 1)] = \
    [0, -3240, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 267, 0, 0, -1]
# pulled from "tactics_work/kalah-results-2-5-0-0-2.json" :
TDATA[(2, 5, 0, 0, 2)] = \
    [0, -260, 864, 0, 0, 1, 0, 0, -1, 4, 0, 0, -1057, -1541, 1, 0, 0, -1]
# pulled from "tactics_work/kalah-results-2-5-0-0-3.json" :
TDATA[(2, 5, 0, 0, 3)] = \
    [0, 0, 0, 1, -1, 0, 0, 1, 0, 0, 0, 4, -1900, 0, 0, 0, 1349, 0]
# pulled from "tactics_work/kalah-results-2-5-0-1-0.json" :
TDATA[(2, 5, 0, 1, 0)] = \
    [-1663, 0, -160, 1776, 0, 0, 0, 0, 0, -1, 1, 5, -437, 374, 1, 0, -395, 696]
# pulled from "tactics_work/kalah-results-2-5-0-1-1.json" :
TDATA[(2, 5, 0, 1, 1)] = \
    [1, -695, 0, 0, 1897, 1, 0, 1, 0, 0, -1, 0, 0, 0, 1, 205, 1800, -634]
# pulled from "tactics_work/kalah-results-2-5-0-1-2.json" :
TDATA[(2, 5, 0, 1, 2)] = \
    [0, 1640, -940, 114, 0, -423, -2, 4, -2, 0, -3, 0, -1, 0, 0, 1733, 617, 1711]
# pulled from "tactics_work/kalah-results-2-5-0-1-3.json" :
TDATA[(2, 5, 0, 1, 3)] = \
    [0, 0, 0, 0, 940, 0, 0, 0, 0, 0, -1, 0, 0, 2, 0, 0, 20, 2656]
# pulled from "tactics_work/kalah-results-2-5-0-2-0.json" :
TDATA[(2, 5, 0, 2, 0)] = \
    [-1, 0, 0, 1214, 0, 0, -1, 3, 0, 0, 0, 1, 0, 0, -1, 986, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-0-2-1.json" :
TDATA[(2, 5, 0, 2, 1)] = \
    [0, 0, 1052, 0, -2, 0, -2, -1, 0, 0, 0, 0, 240, 1, -1500, -503, 1442, -709]
# pulled from "tactics_work/kalah-results-2-5-0-2-2.json" :
TDATA[(2, 5, 0, 2, 2)] = \
    [1262, 0, 1367, 0, 0, -1, -4, 0, -1, 1, -3, 3, -1, 0, 0, 0, 1, 0]
# pulled from "tactics_work/kalah-results-2-5-0-2-3.json" :
TDATA[(2, 5, 0, 2, 3)] = \
    [-188, -1, 0, 0, 695, 0, -5, -4, 0, -1, -1, 0, -3, -588, 407, 1990, 1180, -1]
# pulled from "tactics_work/kalah-results-2-5-3-0-0.json" :
TDATA[(2, 5, 3, 0, 0)] = \
    [0, 0, 1641, 1183, -1, -1, 0, 1, 0, 0, -2, 0, 2322, 0, 1015, 0, -970, 1]
# pulled from "tactics_work/kalah-results-2-5-3-0-1.json" :
TDATA[(2, 5, 3, 0, 1)] = \
    [-556, 0, -1606, -1, 1, 1304, 0, 0, -1, -1, 1, 0, -2176, 1925, 339, 0, -1, -1]
# pulled from "tactics_work/kalah-results-2-5-3-0-2.json" :
TDATA[(2, 5, 3, 0, 2)] = \
    [2, -1, 0, -1, 1639, 1, 4, -4, 1, -1, 0, 0, 0, 0, 0, 0, 735, 0]
# pulled from "tactics_work/kalah-results-2-5-3-0-3.json" :
TDATA[(2, 5, 3, 0, 3)] = \
    [0, 0, -1079, -439, 2, 1913, 2, 1, 0, 0, 3, -1, -1676, -1, 0, 14, -1, -2]
# pulled from "tactics_work/kalah-results-2-5-3-1-0.json" :
TDATA[(2, 5, 3, 1, 0)] = \
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 4, -1, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-1.json" :
TDATA[(2, 5, 3, 1, 1)] = \
    [1, 898, -934, 0, 0, 57, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-2.json" :
TDATA[(2, 5, 3, 1, 2)] = \
    [1, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, -1759, 0, -2, -2, 0]
# pulled from "tactics_work/kalah-results-2-5-3-1-3.json" :
TDATA[(2, 5, 3, 1, 3)] = \
    [-609, -1663, 294, 1529, 0, 0, -3, 1, 0, -1, 0, -2, 1, -1, -1383, -2868, 3059, 753]
# pulled from "tactics_work/kalah-results-2-5-3-2-0.json" :
TDATA[(2, 5, 3, 2, 0)] = \
    [1, 466, 0, 0, 1500, 0, 0, 0, 1, -1, 0, 0, 1, -1648, -2, -1, -2159, -1063]
# pulled from "tactics_work/kalah-results-2-5-3-2-1.json" :
TDATA[(2, 5, 3, 2, 1)] = \
    [-930, 0, 1, 0, 0, -425, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-5-3-2-2.json" :
TDATA[(2, 5, 3, 2, 2)] = \
    [-1712, -1, 1, -1, 846, 0, 3, 0, 0, 0, -1, -1, 0, 446, 813, 0, 0, -1715]
# pulled from "tactics_work/kalah-results-2-5-3-2-3.json" :
TDATA[(2, 5, 3, 2, 3)] = \
    [-314, 1878, 0, 0, -1, 0, 0, 0, -2, 0, 0, -1, -270, 2, 0, -1554, -1662, -957]
# pulled from "tactics_work/kalah-results-2-6-0-0-0.json" :
TDATA[(2, 6, 0, 0, 0)] = \
    [1952, 0, -352, 0, -90, 1, 0, -7, 0, -3, 0, 3, 1, 0, 0, 1590, 1, -1484]
# pulled from "tactics_work/kalah-results-2-6-0-0-1.json" :
TDATA[(2, 6, 0, 0, 1)] = \
    [845, -533, 1895, 698, 434, 0, -7, 3, -2, 3, 2, 1, 0, 1721, -1211, 1, 1942, -1]
# pulled from "tactics_work/kalah-results-2-6-0-0-2.json" :
TDATA[(2, 6, 0, 0, 2)] = \
    [0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 0, 3, 0, 0, -16, 274, 1, 0]
# pulled from "tactics_work/kalah-results-2-6-0-0-3.json" :
TDATA[(2, 6, 0, 0, 3)] = \
    [0, 136, 0, -2533, -1768, -890, 1, 0, -3, -1, -1, -1, 1, -269, -1, 0, 0, -1153]
# pulled from "tactics_work/kalah-results-2-6-0-1-0.json" :
TDATA[(2, 6, 0, 1, 0)] = \
    [-1, 0, 0, -1129, 0, 2888, -3, 0, 0, -2, -1, -1, 0, 0, 922, 0, 872, 0]
# pulled from "tactics_work/kalah-results-2-6-0-1-1.json" :
TDATA[(2, 6, 0, 1, 1)] = \
    [0, -334, 0, -2, 45, -1, 0, -3, -1, -2, 3, -2, 1, -1381, -1918, 0, -1, 161]
# pulled from "tactics_work/kalah-results-2-6-0-1-2.json" :
TDATA[(2, 6, 0, 1, 2)] = \
    [1136, 0, 1637, -1680, -1280, -1, 0, 1, 0, 1, -2, -2, 1716, 1784, -1183, -1768, 791, 1724]
# pulled from "tactics_work/kalah-results-2-6-0-1-3.json" :
TDATA[(2, 6, 0, 1, 3)] = \
    [-716, 0, 0, 1691, -1, -1997, 1, 0, 0, 0, 0, 0, -1, 355, -771, 324, 0, -1377]
# pulled from "tactics_work/kalah-results-2-6-0-2-0.json" :
TDATA[(2, 6, 0, 2, 0)] = \
    [664, 768, -1283, 0, 0, 1, 0, 0, 0, 0, -1, 0, 93, 1, 1673, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-0-2-1.json" :
TDATA[(2, 6, 0, 2, 1)] = \
    [964, -455, 335, 542, -524, -1374, 0, 2, -2, 1, 9, -1, 1805, 1412, 317, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-0-2-2.json" :
TDATA[(2, 6, 0, 2, 2)] = \
    [-963, 1, 1, 0, 1, -44, 1, 0, 0, 0, 1, 1, 1037, 1952, 1, -1, -302, 0]
# pulled from "tactics_work/kalah-results-2-6-0-2-3.json" :
TDATA[(2, 6, 0, 2, 3)] = \
    [0, 93, 0, 0, 418, -695, -3, -4, -2, 0, 0, 0, -759, 3, -1, -1951, -808, 1]
# pulled from "tactics_work/kalah-results-2-6-3-0-0.json" :
TDATA[(2, 6, 3, 0, 0)] = \
    [465, -1612, -1919, 1464, 0, 0, 0, 0, 2, 0, 0, 0, 1, -1, -1, -768, 1502, -1]
# pulled from "tactics_work/kalah-results-2-6-3-0-1.json" :
TDATA[(2, 6, 3, 0, 1)] = \
    [-4776, 0, 0, -1, 855, 0, -1, 0, 0, 0, 0, -1, 0, -1, 1987, 1978, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-0-2.json" :
TDATA[(2, 6, 3, 0, 2)] = \
    [52, 1, -1, -1, -1850, -1, 0, 3, 2, 0, 1, -4, 0, 0, 0, 348, 0, -1]
# pulled from "tactics_work/kalah-results-2-6-3-0-3.json" :
TDATA[(2, 6, 3, 0, 3)] = \
    [0, -1, 0, 0, 550, -676, 4, 0, -1, 1, -1, 0, -1, 0, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-0.json" :
TDATA[(2, 6, 3, 1, 0)] = \
    [0, -305, -1357, 0, 622, 0, -1, 0, 0, -1, 0, 0, 0, -499, 0, 0, -1568, -336]
# pulled from "tactics_work/kalah-results-2-6-3-1-1.json" :
TDATA[(2, 6, 3, 1, 1)] = \
    [0, 0, 0, 532, -247, 0, 3, 0, 1, 1, 0, 0, 0, 1034, 0, 0, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-2.json" :
TDATA[(2, 6, 3, 1, 2)] = \
    [-628, -2, -161, 1237, 1, -51, -1, 0, 0, -1, 1, 0, 0, 0, -782, 1349, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-1-3.json" :
TDATA[(2, 6, 3, 1, 3)] = \
    [-1, 0, 0, 1, 1548, -1614, -4, 0, -1, 0, 0, 1, 0, 0, 0, 899, 0, -578]
# pulled from "tactics_work/kalah-results-2-6-3-2-0.json" :
TDATA[(2, 6, 3, 2, 0)] = \
    [0, 185, 0, 0, 933, 0, 0, 0, -1, 0, 4, 1, -452, 0, -1, 0, 358, 1]
# pulled from "tactics_work/kalah-results-2-6-3-2-1.json" :
TDATA[(2, 6, 3, 2, 1)] = \
    [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, -281, -1547, 0, 1, 0, 0]
# pulled from "tactics_work/kalah-results-2-6-3-2-2.json" :
TDATA[(2, 6, 3, 2, 2)] = \
    [0, 0, -1, 1, 1, 0, 0, -2, -1, 0, 0, 0, 1, -853, -1613, 0, -1, 0]
# pulled from "tactics_work/kalah-results-2-6-3-2-3.json" :
TDATA[(2, 6, 3, 2, 3)] = \
    [-1282, 0, 404, 0, 0, -1702, 0, 1, 2, 0, 0, 1, 0, 1514, 0, -2, 0, -1]

# DO NOT EDIT: autogenerated by "apply_tactics_generated.py"
